/* Copyright 2017 WALLIX

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// DO NOT EDIT
// This file was automatically generated with go generate
package awsspec

var APIPerTemplateDefName = map[string]string{
	"attachalarm":                    "cloudwatch",
	"attachclassicloadbalancer":      "elb",
	"attachcontainertask":            "ecs",
	"attachelasticip":                "ec2",
	"attacheventtarget":              "eventbridge",
	"attachinstance":                 "elbv2",
	"attachinstanceprofile":          "ec2",
	"attachinternetgateway":          "ec2",
	"attachlistener":                 "elbv2",
	"attachmfadevice":                "iam",
	"attachnetworkinterface":         "ec2",
	"attachpolicy":                   "iam",
	"attachrole":                     "iam",
	"attachroutetable":               "ec2",
	"attachsecuritygroup":            "ec2",
	"attachuser":                     "iam",
	"attachvolume":                   "ec2",
	"authenticateregistry":           "ecr",
	"checkcertificate":               "acm",
	"checkdatabase":                  "rds",
	"checkdistribution":              "cloudfront",
	"checkinstance":                  "ec2",
	"checkloadbalancer":              "elbv2",
	"checknatgateway":                "ec2",
	"checknetworkinterface":          "ec2",
	"checkscalinggroup":              "autoscaling",
	"checksecuritygroup":             "ec2",
	"checkvolume":                    "ec2",
	"copyimage":                      "ec2",
	"copysnapshot":                   "ec2",
	"createaccelerator":              "globalaccelerator",
	"createacceleratorlistener":      "globalaccelerator",
	"createaccesskey":                "iam",
	"createalarm":                    "cloudwatch",
	"createapigateway":               "apigatewayv2",
	"createapigatewayroute":          "apigatewayv2",
	"createapigatewaystage":          "apigatewayv2",
	"createapplication":              "elasticbeanstalk",
	"createappscalingpolicy":         "applicationautoscaling",
	"createappscalingtarget":         "applicationautoscaling",
	"createbroker":                   "mq",
	"createbucket":                   "s3",
	"createbuildproject":             "codebuild",
	"createcachecluster":             "elasticache",
	"createcachesubnetgroup":         "elasticache",
	"createcertificate":              "acm",
	"createclassicloadbalancer":      "elb",
	"createconfigrule":               "configservice",
	"createconfigurationset":         "sesv2",
	"createcontainercluster":         "ecs",
	"createcrawler":                  "glue",
	"createdatabase":                 "rds",
	"createdbsubnetgroup":            "rds",
	"createdeployapplication":        "codedeploy",
	"createdeployment":               "codedeploy",
	"createdeploymentgroup":          "codedeploy",
	"createdistribution":             "cloudfront",
	"createdynamodbtable":            "dynamodb",
	"createekscluster":               "eks",
	"createeksnodegroup":             "eks",
	"createelasticip":                "ec2",
	"createemailidentity":            "sesv2",
	"createenvironment":              "elasticbeanstalk",
	"createeventbus":                 "eventbridge",
	"createeventrule":                "eventbridge",
	"createfilesystem":               "efs",
	"createfsxbackup":                "fsx",
	"createfsxfilesystem":            "fsx",
	"createfunction":                 "lambda",
	"creategluedatabase":             "glue",
	"creategroup":                    "iam",
	"createidentitypool":             "cognitoidentity",
	"createimage":                    "ec2",
	"createinstance":                 "ec2",
	"createinstanceprofile":          "iam",
	"createinternetgateway":          "ec2",
	"createipset":                    "wafv2",
	"createjob":                      "glue",
	"createkafkacluster":             "kafka",
	"createkeypair":                  "ec2",
	"createlaunchconfiguration":      "autoscaling",
	"createlistener":                 "elbv2",
	"createloadbalancer":             "elbv2",
	"createloggroup":                 "cloudwatchlogs",
	"createloginprofile":             "iam",
	"createmfadevice":                "iam",
	"createnatgateway":               "ec2",
	"createnetworkinterface":         "ec2",
	"createpipeline":                 "codepipeline",
	"createpolicy":                   "iam",
	"createqueue":                    "sqs",
	"createrecord":                   "route53",
	"createredshiftcluster":          "redshift",
	"createredshiftsubnetgroup":      "redshift",
	"createreplicationgroup":         "elasticache",
	"createrepository":               "ecr",
	"createrole":                     "iam",
	"createroute":                    "ec2",
	"createroutetable":               "ec2",
	"createrulegroup":                "wafv2",
	"creates3object":                 "s3",
	"createscalinggroup":             "autoscaling",
	"createscalingpolicy":            "autoscaling",
	"createsecret":                   "secretsmanager",
	"createsecuritygroup":            "ec2",
	"createsnapshot":                 "ec2",
	"createssmparameter":             "ssm",
	"createstack":                    "cloudformation",
	"createstatemachine":             "sfn",
	"createstream":                   "kinesis",
	"createsubnet":                   "ec2",
	"createsubscription":             "sns",
	"createtag":                      "ec2",
	"createtargetgroup":              "elbv2",
	"createtopic":                    "sns",
	"createtrail":                    "cloudtrail",
	"createtransitgateway":           "ec2",
	"createtransitgatewayattachment": "ec2",
	"createtransitgatewayroutetable": "ec2",
	"createuser":                     "iam",
	"createuserpool":                 "cognitoidentityprovider",
	"createvolume":                   "ec2",
	"createvpc":                      "ec2",
	"createvpcendpoint":              "ec2",
	"createwebacl":                   "wafv2",
	"createzone":                     "route53",
	"deleteaccelerator":              "globalaccelerator",
	"deleteacceleratorlistener":      "globalaccelerator",
	"deleteaccesskey":                "iam",
	"deletealarm":                    "cloudwatch",
	"deleteapigateway":               "apigatewayv2",
	"deleteapigatewayroute":          "apigatewayv2",
	"deleteapigatewaystage":          "apigatewayv2",
	"deleteapplication":              "elasticbeanstalk",
	"deleteappscalingpolicy":         "applicationautoscaling",
	"deleteappscalingtarget":         "applicationautoscaling",
	"deletebroker":                   "mq",
	"deletebucket":                   "s3",
	"deletebuildproject":             "codebuild",
	"deletecachecluster":             "elasticache",
	"deletecachesubnetgroup":         "elasticache",
	"deletecertificate":              "acm",
	"deleteclassicloadbalancer":      "elb",
	"deleteconfigrule":               "configservice",
	"deleteconfigurationset":         "sesv2",
	"deletecontainercluster":         "ecs",
	"deletecontainertask":            "ecs",
	"deletecrawler":                  "glue",
	"deletedatabase":                 "rds",
	"deletedbsubnetgroup":            "rds",
	"deletedeployapplication":        "codedeploy",
	"deletedeploymentgroup":          "codedeploy",
	"deletedistribution":             "cloudfront",
	"deletedynamodbtable":            "dynamodb",
	"deleteekscluster":               "eks",
	"deleteeksnodegroup":             "eks",
	"deleteelasticip":                "ec2",
	"deleteemailidentity":            "sesv2",
	"deleteenvironment":              "elasticbeanstalk",
	"deleteeventbus":                 "eventbridge",
	"deleteeventrule":                "eventbridge",
	"deletefilesystem":               "efs",
	"deletefsxbackup":                "fsx",
	"deletefsxfilesystem":            "fsx",
	"deletefunction":                 "lambda",
	"deletegluedatabase":             "glue",
	"deletegroup":                    "iam",
	"deleteidentitypool":             "cognitoidentity",
	"deleteimage":                    "ec2",
	"deleteinstance":                 "ec2",
	"deleteinstanceprofile":          "iam",
	"deleteinternetgateway":          "ec2",
	"deleteipset":                    "wafv2",
	"deletejob":                      "glue",
	"deletekafkacluster":             "kafka",
	"deletekeypair":                  "ec2",
	"deletelaunchconfiguration":      "autoscaling",
	"deletelistener":                 "elbv2",
	"deleteloadbalancer":             "elbv2",
	"deleteloggroup":                 "cloudwatchlogs",
	"deleteloginprofile":             "iam",
	"deletemfadevice":                "iam",
	"deletenatgateway":               "ec2",
	"deletenetworkinterface":         "ec2",
	"deletepipeline":                 "codepipeline",
	"deletepolicy":                   "iam",
	"deletequeue":                    "sqs",
	"deleterecord":                   "route53",
	"deleteredshiftcluster":          "redshift",
	"deleteredshiftsubnetgroup":      "redshift",
	"deletereplicationgroup":         "elasticache",
	"deleterepository":               "ecr",
	"deleterole":                     "iam",
	"deleteroute":                    "ec2",
	"deleteroutetable":               "ec2",
	"deleterulegroup":                "wafv2",
	"deletes3object":                 "s3",
	"deletescalinggroup":             "autoscaling",
	"deletescalingpolicy":            "autoscaling",
	"deletesecret":                   "secretsmanager",
	"deletesecuritygroup":            "ec2",
	"deletesnapshot":                 "ec2",
	"deletessmparameter":             "ssm",
	"deletestack":                    "cloudformation",
	"deletestatemachine":             "sfn",
	"deletestream":                   "kinesis",
	"deletesubnet":                   "ec2",
	"deletesubscription":             "sns",
	"deletetag":                      "ec2",
	"deletetargetgroup":              "elbv2",
	"deletetopic":                    "sns",
	"deletetrail":                    "cloudtrail",
	"deletetransitgateway":           "ec2",
	"deletetransitgatewayattachment": "ec2",
	"deletetransitgatewayroutetable": "ec2",
	"deleteuser":                     "iam",
	"deleteuserpool":                 "cognitoidentityprovider",
	"deletevolume":                   "ec2",
	"deletevpc":                      "ec2",
	"deletevpcendpoint":              "ec2",
	"deletewebacl":                   "wafv2",
	"deletezone":                     "route53",
	"detachalarm":                    "cloudwatch",
	"detachclassicloadbalancer":      "elb",
	"detachcontainertask":            "ecs",
	"detachelasticip":                "ec2",
	"detacheventtarget":              "eventbridge",
	"detachinstance":                 "elbv2",
	"detachinstanceprofile":          "ec2",
	"detachinternetgateway":          "ec2",
	"detachmfadevice":                "iam",
	"detachnetworkinterface":         "ec2",
	"detachpolicy":                   "iam",
	"detachrole":                     "iam",
	"detachroutetable":               "ec2",
	"detachsecuritygroup":            "ec2",
	"detachuser":                     "iam",
	"detachvolume":                   "ec2",
	"importimage":                    "ec2",
	"restartdatabase":                "rds",
	"restartinstance":                "ec2",
	"startalarm":                     "cloudwatch",
	"startbuildproject":              "codebuild",
	"startcontainertask":             "ecs",
	"startcrawler":                   "glue",
	"startdatabase":                  "rds",
	"starteventrule":                 "eventbridge",
	"startexecution":                 "sfn",
	"startinstance":                  "ec2",
	"startjob":                       "glue",
	"startpipeline":                  "codepipeline",
	"starttrail":                     "cloudtrail",
	"stopalarm":                      "cloudwatch",
	"stopbuildproject":               "codebuild",
	"stopcontainertask":              "ecs",
	"stopcrawler":                    "glue",
	"stopdatabase":                   "rds",
	"stopdeployment":                 "codedeploy",
	"stopeventrule":                  "eventbridge",
	"stopexecution":                  "sfn",
	"stopinstance":                   "ec2",
	"stoppipeline":                   "codepipeline",
	"stoptrail":                      "cloudtrail",
	"updateaccelerator":              "globalaccelerator",
	"updateapplication":              "elasticbeanstalk",
	"updatebucket":                   "s3",
	"updatebuildproject":             "codebuild",
	"updatecachecluster":             "elasticache",
	"updatecachesubnetgroup":         "elasticache",
	"updateclassicloadbalancer":      "elb",
	"updateconfigrule":               "configservice",
	"updatecontainertask":            "ecs",
	"updatedistribution":             "cloudfront",
	"updateenvironment":              "elasticbeanstalk",
	"updateeventrule":                "eventbridge",
	"updateimage":                    "ec2",
	"updateinstance":                 "ec2",
	"updateipset":                    "wafv2",
	"updateloggroup":                 "cloudwatchlogs",
	"updateloginprofile":             "iam",
	"updatepolicy":                   "iam",
	"updaterecord":                   "route53",
	"updateredshiftcluster":          "redshift",
	"updates3object":                 "s3",
	"updatescalinggroup":             "autoscaling",
	"updatesecret":                   "secretsmanager",
	"updatesecuritygroup":            "ec2",
	"updatessmparameter":             "ssm",
	"updatestack":                    "cloudformation",
	"updatestatemachine":             "sfn",
	"updatestream":                   "kinesis",
	"updatesubnet":                   "ec2",
	"updatetargetgroup":              "elbv2",
}

var AWSTemplatesDefinitions = map[string]Definition{
	"attachalarm": Definition{
		Action: "attach",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(AttachAlarm).ParamsSpec().Rule(),
	},
	"attachclassicloadbalancer": Definition{
		Action: "attach",
		Entity: "classicloadbalancer",
		API:    "elb",
		Params: new(AttachClassicLoadbalancer).ParamsSpec().Rule(),
	},
	"attachcontainertask": Definition{
		Action: "attach",
		Entity: "containertask",
		API:    "ecs",
		Params: new(AttachContainertask).ParamsSpec().Rule(),
	},
	"attachelasticip": Definition{
		Action: "attach",
		Entity: "elasticip",
		API:    "ec2",
		Params: new(AttachElasticip).ParamsSpec().Rule(),
	},
	"attacheventtarget": Definition{
		Action: "attach",
		Entity: "eventtarget",
		API:    "eventbridge",
		Params: new(AttachEventtarget).ParamsSpec().Rule(),
	},
	"attachinstance": Definition{
		Action: "attach",
		Entity: "instance",
		API:    "elbv2",
		Params: new(AttachInstance).ParamsSpec().Rule(),
	},
	"attachinstanceprofile": Definition{
		Action: "attach",
		Entity: "instanceprofile",
		API:    "ec2",
		Params: new(AttachInstanceprofile).ParamsSpec().Rule(),
	},
	"attachinternetgateway": Definition{
		Action: "attach",
		Entity: "internetgateway",
		API:    "ec2",
		Params: new(AttachInternetgateway).ParamsSpec().Rule(),
	},
	"attachlistener": Definition{
		Action: "attach",
		Entity: "listener",
		API:    "elbv2",
		Params: new(AttachListener).ParamsSpec().Rule(),
	},
	"attachmfadevice": Definition{
		Action: "attach",
		Entity: "mfadevice",
		API:    "iam",
		Params: new(AttachMfadevice).ParamsSpec().Rule(),
	},
	"attachnetworkinterface": Definition{
		Action: "attach",
		Entity: "networkinterface",
		API:    "ec2",
		Params: new(AttachNetworkinterface).ParamsSpec().Rule(),
	},
	"attachpolicy": Definition{
		Action: "attach",
		Entity: "policy",
		API:    "iam",
		Params: new(AttachPolicy).ParamsSpec().Rule(),
	},
	"attachrole": Definition{
		Action: "attach",
		Entity: "role",
		API:    "iam",
		Params: new(AttachRole).ParamsSpec().Rule(),
	},
	"attachroutetable": Definition{
		Action: "attach",
		Entity: "routetable",
		API:    "ec2",
		Params: new(AttachRoutetable).ParamsSpec().Rule(),
	},
	"attachsecuritygroup": Definition{
		Action: "attach",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(AttachSecuritygroup).ParamsSpec().Rule(),
	},
	"attachuser": Definition{
		Action: "attach",
		Entity: "user",
		API:    "iam",
		Params: new(AttachUser).ParamsSpec().Rule(),
	},
	"attachvolume": Definition{
		Action: "attach",
		Entity: "volume",
		API:    "ec2",
		Params: new(AttachVolume).ParamsSpec().Rule(),
	},
	"authenticateregistry": Definition{
		Action: "authenticate",
		Entity: "registry",
		API:    "ecr",
		Params: new(AuthenticateRegistry).ParamsSpec().Rule(),
	},
	"checkcertificate": Definition{
		Action: "check",
		Entity: "certificate",
		API:    "acm",
		Params: new(CheckCertificate).ParamsSpec().Rule(),
	},
	"checkdatabase": Definition{
		Action: "check",
		Entity: "database",
		API:    "rds",
		Params: new(CheckDatabase).ParamsSpec().Rule(),
	},
	"checkdistribution": Definition{
		Action: "check",
		Entity: "distribution",
		API:    "cloudfront",
		Params: new(CheckDistribution).ParamsSpec().Rule(),
	},
	"checkinstance": Definition{
		Action: "check",
		Entity: "instance",
		API:    "ec2",
		Params: new(CheckInstance).ParamsSpec().Rule(),
	},
	"checkloadbalancer": Definition{
		Action: "check",
		Entity: "loadbalancer",
		API:    "elbv2",
		Params: new(CheckLoadbalancer).ParamsSpec().Rule(),
	},
	"checknatgateway": Definition{
		Action: "check",
		Entity: "natgateway",
		API:    "ec2",
		Params: new(CheckNatgateway).ParamsSpec().Rule(),
	},
	"checknetworkinterface": Definition{
		Action: "check",
		Entity: "networkinterface",
		API:    "ec2",
		Params: new(CheckNetworkinterface).ParamsSpec().Rule(),
	},
	"checkscalinggroup": Definition{
		Action: "check",
		Entity: "scalinggroup",
		API:    "autoscaling",
		Params: new(CheckScalinggroup).ParamsSpec().Rule(),
	},
	"checksecuritygroup": Definition{
		Action: "check",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(CheckSecuritygroup).ParamsSpec().Rule(),
	},
	"checkvolume": Definition{
		Action: "check",
		Entity: "volume",
		API:    "ec2",
		Params: new(CheckVolume).ParamsSpec().Rule(),
	},
	"copyimage": Definition{
		Action: "copy",
		Entity: "image",
		API:    "ec2",
		Params: new(CopyImage).ParamsSpec().Rule(),
	},
	"copysnapshot": Definition{
		Action: "copy",
		Entity: "snapshot",
		API:    "ec2",
		Params: new(CopySnapshot).ParamsSpec().Rule(),
	},
	"createaccelerator": Definition{
		Action: "create",
		Entity: "accelerator",
		API:    "globalaccelerator",
		Params: new(CreateAccelerator).ParamsSpec().Rule(),
	},
	"createacceleratorlistener": Definition{
		Action: "create",
		Entity: "acceleratorlistener",
		API:    "globalaccelerator",
		Params: new(CreateAcceleratorlistener).ParamsSpec().Rule(),
	},
	"createaccesskey": Definition{
		Action: "create",
		Entity: "accesskey",
		API:    "iam",
		Params: new(CreateAccesskey).ParamsSpec().Rule(),
	},
	"createalarm": Definition{
		Action: "create",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(CreateAlarm).ParamsSpec().Rule(),
	},
	"createapigateway": Definition{
		Action: "create",
		Entity: "apigateway",
		API:    "apigatewayv2",
		Params: new(CreateApigateway).ParamsSpec().Rule(),
	},
	"createapigatewayroute": Definition{
		Action: "create",
		Entity: "apigatewayroute",
		API:    "apigatewayv2",
		Params: new(CreateApigatewayroute).ParamsSpec().Rule(),
	},
	"createapigatewaystage": Definition{
		Action: "create",
		Entity: "apigatewaystage",
		API:    "apigatewayv2",
		Params: new(CreateApigatewaystage).ParamsSpec().Rule(),
	},
	"createapplication": Definition{
		Action: "create",
		Entity: "application",
		API:    "elasticbeanstalk",
		Params: new(CreateApplication).ParamsSpec().Rule(),
	},
	"createappscalingpolicy": Definition{
		Action: "create",
		Entity: "appscalingpolicy",
		API:    "applicationautoscaling",
		Params: new(CreateAppscalingpolicy).ParamsSpec().Rule(),
	},
	"createappscalingtarget": Definition{
		Action: "create",
		Entity: "appscalingtarget",
		API:    "applicationautoscaling",
		Params: new(CreateAppscalingtarget).ParamsSpec().Rule(),
	},
	"createbroker": Definition{
		Action: "create",
		Entity: "broker",
		API:    "mq",
		Params: new(CreateBroker).ParamsSpec().Rule(),
	},
	"createbucket": Definition{
		Action: "create",
		Entity: "bucket",
		API:    "s3",
		Params: new(CreateBucket).ParamsSpec().Rule(),
	},
	"createbuildproject": Definition{
		Action: "create",
		Entity: "buildproject",
		API:    "codebuild",
		Params: new(CreateBuildproject).ParamsSpec().Rule(),
	},
	"createcachecluster": Definition{
		Action: "create",
		Entity: "cachecluster",
		API:    "elasticache",
		Params: new(CreateCachecluster).ParamsSpec().Rule(),
	},
	"createcachesubnetgroup": Definition{
		Action: "create",
		Entity: "cachesubnetgroup",
		API:    "elasticache",
		Params: new(CreateCachesubnetgroup).ParamsSpec().Rule(),
	},
	"createcertificate": Definition{
		Action: "create",
		Entity: "certificate",
		API:    "acm",
		Params: new(CreateCertificate).ParamsSpec().Rule(),
	},
	"createclassicloadbalancer": Definition{
		Action: "create",
		Entity: "classicloadbalancer",
		API:    "elb",
		Params: new(CreateClassicLoadbalancer).ParamsSpec().Rule(),
	},
	"createconfigrule": Definition{
		Action: "create",
		Entity: "configrule",
		API:    "configservice",
		Params: new(CreateConfigrule).ParamsSpec().Rule(),
	},
	"createconfigurationset": Definition{
		Action: "create",
		Entity: "configurationset",
		API:    "sesv2",
		Params: new(CreateConfigurationset).ParamsSpec().Rule(),
	},
	"createcontainercluster": Definition{
		Action: "create",
		Entity: "containercluster",
		API:    "ecs",
		Params: new(CreateContainercluster).ParamsSpec().Rule(),
	},
	"createcrawler": Definition{
		Action: "create",
		Entity: "crawler",
		API:    "glue",
		Params: new(CreateCrawler).ParamsSpec().Rule(),
	},
	"createdatabase": Definition{
		Action: "create",
		Entity: "database",
		API:    "rds",
		Params: new(CreateDatabase).ParamsSpec().Rule(),
	},
	"createdbsubnetgroup": Definition{
		Action: "create",
		Entity: "dbsubnetgroup",
		API:    "rds",
		Params: new(CreateDbsubnetgroup).ParamsSpec().Rule(),
	},
	"createdeployapplication": Definition{
		Action: "create",
		Entity: "deployapplication",
		API:    "codedeploy",
		Params: new(CreateDeployapplication).ParamsSpec().Rule(),
	},
	"createdeployment": Definition{
		Action: "create",
		Entity: "deployment",
		API:    "codedeploy",
		Params: new(CreateDeployment).ParamsSpec().Rule(),
	},
	"createdeploymentgroup": Definition{
		Action: "create",
		Entity: "deploymentgroup",
		API:    "codedeploy",
		Params: new(CreateDeploymentgroup).ParamsSpec().Rule(),
	},
	"createdistribution": Definition{
		Action: "create",
		Entity: "distribution",
		API:    "cloudfront",
		Params: new(CreateDistribution).ParamsSpec().Rule(),
	},
	"createdynamodbtable": Definition{
		Action: "create",
		Entity: "dynamodbtable",
		API:    "dynamodb",
		Params: new(CreateDynamodbtable).ParamsSpec().Rule(),
	},
	"createekscluster": Definition{
		Action: "create",
		Entity: "ekscluster",
		API:    "eks",
		Params: new(CreateEkscluster).ParamsSpec().Rule(),
	},
	"createeksnodegroup": Definition{
		Action: "create",
		Entity: "eksnodegroup",
		API:    "eks",
		Params: new(CreateEksnodegroup).ParamsSpec().Rule(),
	},
	"createelasticip": Definition{
		Action: "create",
		Entity: "elasticip",
		API:    "ec2",
		Params: new(CreateElasticip).ParamsSpec().Rule(),
	},
	"createemailidentity": Definition{
		Action: "create",
		Entity: "emailidentity",
		API:    "sesv2",
		Params: new(CreateEmailidentity).ParamsSpec().Rule(),
	},
	"createenvironment": Definition{
		Action: "create",
		Entity: "environment",
		API:    "elasticbeanstalk",
		Params: new(CreateEnvironment).ParamsSpec().Rule(),
	},
	"createeventbus": Definition{
		Action: "create",
		Entity: "eventbus",
		API:    "eventbridge",
		Params: new(CreateEventbus).ParamsSpec().Rule(),
	},
	"createeventrule": Definition{
		Action: "create",
		Entity: "eventrule",
		API:    "eventbridge",
		Params: new(CreateEventrule).ParamsSpec().Rule(),
	},
	"createfilesystem": Definition{
		Action: "create",
		Entity: "filesystem",
		API:    "efs",
		Params: new(CreateFilesystem).ParamsSpec().Rule(),
	},
	"createfsxbackup": Definition{
		Action: "create",
		Entity: "fsxbackup",
		API:    "fsx",
		Params: new(CreateFsxbackup).ParamsSpec().Rule(),
	},
	"createfsxfilesystem": Definition{
		Action: "create",
		Entity: "fsxfilesystem",
		API:    "fsx",
		Params: new(CreateFsxfilesystem).ParamsSpec().Rule(),
	},
	"createfunction": Definition{
		Action: "create",
		Entity: "function",
		API:    "lambda",
		Params: new(CreateFunction).ParamsSpec().Rule(),
	},
	"creategluedatabase": Definition{
		Action: "create",
		Entity: "gluedatabase",
		API:    "glue",
		Params: new(CreateGluedatabase).ParamsSpec().Rule(),
	},
	"creategroup": Definition{
		Action: "create",
		Entity: "group",
		API:    "iam",
		Params: new(CreateGroup).ParamsSpec().Rule(),
	},
	"createidentitypool": Definition{
		Action: "create",
		Entity: "identitypool",
		API:    "cognitoidentity",
		Params: new(CreateIdentitypool).ParamsSpec().Rule(),
	},
	"createimage": Definition{
		Action: "create",
		Entity: "image",
		API:    "ec2",
		Params: new(CreateImage).ParamsSpec().Rule(),
	},
	"createinstance": Definition{
		Action: "create",
		Entity: "instance",
		API:    "ec2",
		Params: new(CreateInstance).ParamsSpec().Rule(),
	},
	"createinstanceprofile": Definition{
		Action: "create",
		Entity: "instanceprofile",
		API:    "iam",
		Params: new(CreateInstanceprofile).ParamsSpec().Rule(),
	},
	"createinternetgateway": Definition{
		Action: "create",
		Entity: "internetgateway",
		API:    "ec2",
		Params: new(CreateInternetgateway).ParamsSpec().Rule(),
	},
	"createipset": Definition{
		Action: "create",
		Entity: "ipset",
		API:    "wafv2",
		Params: new(CreateIpset).ParamsSpec().Rule(),
	},
	"createjob": Definition{
		Action: "create",
		Entity: "job",
		API:    "glue",
		Params: new(CreateJob).ParamsSpec().Rule(),
	},
	"createkafkacluster": Definition{
		Action: "create",
		Entity: "kafkacluster",
		API:    "kafka",
		Params: new(CreateKafkacluster).ParamsSpec().Rule(),
	},
	"createkeypair": Definition{
		Action: "create",
		Entity: "keypair",
		API:    "ec2",
		Params: new(CreateKeypair).ParamsSpec().Rule(),
	},
	"createlaunchconfiguration": Definition{
		Action: "create",
		Entity: "launchconfiguration",
		API:    "autoscaling",
		Params: new(CreateLaunchconfiguration).ParamsSpec().Rule(),
	},
	"createlistener": Definition{
		Action: "create",
		Entity: "listener",
		API:    "elbv2",
		Params: new(CreateListener).ParamsSpec().Rule(),
	},
	"createloadbalancer": Definition{
		Action: "create",
		Entity: "loadbalancer",
		API:    "elbv2",
		Params: new(CreateLoadbalancer).ParamsSpec().Rule(),
	},
	"createloggroup": Definition{
		Action: "create",
		Entity: "loggroup",
		API:    "cloudwatchlogs",
		Params: new(CreateLoggroup).ParamsSpec().Rule(),
	},
	"createloginprofile": Definition{
		Action: "create",
		Entity: "loginprofile",
		API:    "iam",
		Params: new(CreateLoginprofile).ParamsSpec().Rule(),
	},
	"createmfadevice": Definition{
		Action: "create",
		Entity: "mfadevice",
		API:    "iam",
		Params: new(CreateMfadevice).ParamsSpec().Rule(),
	},
	"createnatgateway": Definition{
		Action: "create",
		Entity: "natgateway",
		API:    "ec2",
		Params: new(CreateNatgateway).ParamsSpec().Rule(),
	},
	"createnetworkinterface": Definition{
		Action: "create",
		Entity: "networkinterface",
		API:    "ec2",
		Params: new(CreateNetworkinterface).ParamsSpec().Rule(),
	},
	"createpipeline": Definition{
		Action: "create",
		Entity: "pipeline",
		API:    "codepipeline",
		Params: new(CreatePipeline).ParamsSpec().Rule(),
	},
	"createpolicy": Definition{
		Action: "create",
		Entity: "policy",
		API:    "iam",
		Params: new(CreatePolicy).ParamsSpec().Rule(),
	},
	"createqueue": Definition{
		Action: "create",
		Entity: "queue",
		API:    "sqs",
		Params: new(CreateQueue).ParamsSpec().Rule(),
	},
	"createrecord": Definition{
		Action: "create",
		Entity: "record",
		API:    "route53",
		Params: new(CreateRecord).ParamsSpec().Rule(),
	},
	"createredshiftcluster": Definition{
		Action: "create",
		Entity: "redshiftcluster",
		API:    "redshift",
		Params: new(CreateRedshiftcluster).ParamsSpec().Rule(),
	},
	"createredshiftsubnetgroup": Definition{
		Action: "create",
		Entity: "redshiftsubnetgroup",
		API:    "redshift",
		Params: new(CreateRedshiftsubnetgroup).ParamsSpec().Rule(),
	},
	"createreplicationgroup": Definition{
		Action: "create",
		Entity: "replicationgroup",
		API:    "elasticache",
		Params: new(CreateReplicationgroup).ParamsSpec().Rule(),
	},
	"createrepository": Definition{
		Action: "create",
		Entity: "repository",
		API:    "ecr",
		Params: new(CreateRepository).ParamsSpec().Rule(),
	},
	"createrole": Definition{
		Action: "create",
		Entity: "role",
		API:    "iam",
		Params: new(CreateRole).ParamsSpec().Rule(),
	},
	"createroute": Definition{
		Action: "create",
		Entity: "route",
		API:    "ec2",
		Params: new(CreateRoute).ParamsSpec().Rule(),
	},
	"createroutetable": Definition{
		Action: "create",
		Entity: "routetable",
		API:    "ec2",
		Params: new(CreateRoutetable).ParamsSpec().Rule(),
	},
	"createrulegroup": Definition{
		Action: "create",
		Entity: "rulegroup",
		API:    "wafv2",
		Params: new(CreateRulegroup).ParamsSpec().Rule(),
	},
	"creates3object": Definition{
		Action: "create",
		Entity: "s3object",
		API:    "s3",
		Params: new(CreateS3object).ParamsSpec().Rule(),
	},
	"createscalinggroup": Definition{
		Action: "create",
		Entity: "scalinggroup",
		API:    "autoscaling",
		Params: new(CreateScalinggroup).ParamsSpec().Rule(),
	},
	"createscalingpolicy": Definition{
		Action: "create",
		Entity: "scalingpolicy",
		API:    "autoscaling",
		Params: new(CreateScalingpolicy).ParamsSpec().Rule(),
	},
	"createsecret": Definition{
		Action: "create",
		Entity: "secret",
		API:    "secretsmanager",
		Params: new(CreateSecret).ParamsSpec().Rule(),
	},
	"createsecuritygroup": Definition{
		Action: "create",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(CreateSecuritygroup).ParamsSpec().Rule(),
	},
	"createsnapshot": Definition{
		Action: "create",
		Entity: "snapshot",
		API:    "ec2",
		Params: new(CreateSnapshot).ParamsSpec().Rule(),
	},
	"createssmparameter": Definition{
		Action: "create",
		Entity: "ssmparameter",
		API:    "ssm",
		Params: new(CreateSsmparameter).ParamsSpec().Rule(),
	},
	"createstack": Definition{
		Action: "create",
		Entity: "stack",
		API:    "cloudformation",
		Params: new(CreateStack).ParamsSpec().Rule(),
	},
	"createstatemachine": Definition{
		Action: "create",
		Entity: "statemachine",
		API:    "sfn",
		Params: new(CreateStatemachine).ParamsSpec().Rule(),
	},
	"createstream": Definition{
		Action: "create",
		Entity: "stream",
		API:    "kinesis",
		Params: new(CreateStream).ParamsSpec().Rule(),
	},
	"createsubnet": Definition{
		Action: "create",
		Entity: "subnet",
		API:    "ec2",
		Params: new(CreateSubnet).ParamsSpec().Rule(),
	},
	"createsubscription": Definition{
		Action: "create",
		Entity: "subscription",
		API:    "sns",
		Params: new(CreateSubscription).ParamsSpec().Rule(),
	},
	"createtag": Definition{
		Action: "create",
		Entity: "tag",
		API:    "ec2",
		Params: new(CreateTag).ParamsSpec().Rule(),
	},
	"createtargetgroup": Definition{
		Action: "create",
		Entity: "targetgroup",
		API:    "elbv2",
		Params: new(CreateTargetgroup).ParamsSpec().Rule(),
	},
	"createtopic": Definition{
		Action: "create",
		Entity: "topic",
		API:    "sns",
		Params: new(CreateTopic).ParamsSpec().Rule(),
	},
	"createtrail": Definition{
		Action: "create",
		Entity: "trail",
		API:    "cloudtrail",
		Params: new(CreateTrail).ParamsSpec().Rule(),
	},
	"createtransitgateway": Definition{
		Action: "create",
		Entity: "transitgateway",
		API:    "ec2",
		Params: new(CreateTransitgateway).ParamsSpec().Rule(),
	},
	"createtransitgatewayattachment": Definition{
		Action: "create",
		Entity: "transitgatewayattachment",
		API:    "ec2",
		Params: new(CreateTransitgatewayattachment).ParamsSpec().Rule(),
	},
	"createtransitgatewayroutetable": Definition{
		Action: "create",
		Entity: "transitgatewayroutetable",
		API:    "ec2",
		Params: new(CreateTransitgatewayroutetable).ParamsSpec().Rule(),
	},
	"createuser": Definition{
		Action: "create",
		Entity: "user",
		API:    "iam",
		Params: new(CreateUser).ParamsSpec().Rule(),
	},
	"createuserpool": Definition{
		Action: "create",
		Entity: "userpool",
		API:    "cognitoidentityprovider",
		Params: new(CreateUserpool).ParamsSpec().Rule(),
	},
	"createvolume": Definition{
		Action: "create",
		Entity: "volume",
		API:    "ec2",
		Params: new(CreateVolume).ParamsSpec().Rule(),
	},
	"createvpc": Definition{
		Action: "create",
		Entity: "vpc",
		API:    "ec2",
		Params: new(CreateVpc).ParamsSpec().Rule(),
	},
	"createvpcendpoint": Definition{
		Action: "create",
		Entity: "vpcendpoint",
		API:    "ec2",
		Params: new(CreateVpcendpoint).ParamsSpec().Rule(),
	},
	"createwebacl": Definition{
		Action: "create",
		Entity: "webacl",
		API:    "wafv2",
		Params: new(CreateWebacl).ParamsSpec().Rule(),
	},
	"createzone": Definition{
		Action: "create",
		Entity: "zone",
		API:    "route53",
		Params: new(CreateZone).ParamsSpec().Rule(),
	},
	"deleteaccelerator": Definition{
		Action: "delete",
		Entity: "accelerator",
		API:    "globalaccelerator",
		Params: new(DeleteAccelerator).ParamsSpec().Rule(),
	},
	"deleteacceleratorlistener": Definition{
		Action: "delete",
		Entity: "acceleratorlistener",
		API:    "globalaccelerator",
		Params: new(DeleteAcceleratorlistener).ParamsSpec().Rule(),
	},
	"deleteaccesskey": Definition{
		Action: "delete",
		Entity: "accesskey",
		API:    "iam",
		Params: new(DeleteAccesskey).ParamsSpec().Rule(),
	},
	"deletealarm": Definition{
		Action: "delete",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(DeleteAlarm).ParamsSpec().Rule(),
	},
	"deleteapigateway": Definition{
		Action: "delete",
		Entity: "apigateway",
		API:    "apigatewayv2",
		Params: new(DeleteApigateway).ParamsSpec().Rule(),
	},
	"deleteapigatewayroute": Definition{
		Action: "delete",
		Entity: "apigatewayroute",
		API:    "apigatewayv2",
		Params: new(DeleteApigatewayroute).ParamsSpec().Rule(),
	},
	"deleteapigatewaystage": Definition{
		Action: "delete",
		Entity: "apigatewaystage",
		API:    "apigatewayv2",
		Params: new(DeleteApigatewaystage).ParamsSpec().Rule(),
	},
	"deleteapplication": Definition{
		Action: "delete",
		Entity: "application",
		API:    "elasticbeanstalk",
		Params: new(DeleteApplication).ParamsSpec().Rule(),
	},
	"deleteappscalingpolicy": Definition{
		Action: "delete",
		Entity: "appscalingpolicy",
		API:    "applicationautoscaling",
		Params: new(DeleteAppscalingpolicy).ParamsSpec().Rule(),
	},
	"deleteappscalingtarget": Definition{
		Action: "delete",
		Entity: "appscalingtarget",
		API:    "applicationautoscaling",
		Params: new(DeleteAppscalingtarget).ParamsSpec().Rule(),
	},
	"deletebroker": Definition{
		Action: "delete",
		Entity: "broker",
		API:    "mq",
		Params: new(DeleteBroker).ParamsSpec().Rule(),
	},
	"deletebucket": Definition{
		Action: "delete",
		Entity: "bucket",
		API:    "s3",
		Params: new(DeleteBucket).ParamsSpec().Rule(),
	},
	"deletebuildproject": Definition{
		Action: "delete",
		Entity: "buildproject",
		API:    "codebuild",
		Params: new(DeleteBuildproject).ParamsSpec().Rule(),
	},
	"deletecachecluster": Definition{
		Action: "delete",
		Entity: "cachecluster",
		API:    "elasticache",
		Params: new(DeleteCachecluster).ParamsSpec().Rule(),
	},
	"deletecachesubnetgroup": Definition{
		Action: "delete",
		Entity: "cachesubnetgroup",
		API:    "elasticache",
		Params: new(DeleteCachesubnetgroup).ParamsSpec().Rule(),
	},
	"deletecertificate": Definition{
		Action: "delete",
		Entity: "certificate",
		API:    "acm",
		Params: new(DeleteCertificate).ParamsSpec().Rule(),
	},
	"deleteclassicloadbalancer": Definition{
		Action: "delete",
		Entity: "classicloadbalancer",
		API:    "elb",
		Params: new(DeleteClassicLoadbalancer).ParamsSpec().Rule(),
	},
	"deleteconfigrule": Definition{
		Action: "delete",
		Entity: "configrule",
		API:    "configservice",
		Params: new(DeleteConfigrule).ParamsSpec().Rule(),
	},
	"deleteconfigurationset": Definition{
		Action: "delete",
		Entity: "configurationset",
		API:    "sesv2",
		Params: new(DeleteConfigurationset).ParamsSpec().Rule(),
	},
	"deletecontainercluster": Definition{
		Action: "delete",
		Entity: "containercluster",
		API:    "ecs",
		Params: new(DeleteContainercluster).ParamsSpec().Rule(),
	},
	"deletecontainertask": Definition{
		Action: "delete",
		Entity: "containertask",
		API:    "ecs",
		Params: new(DeleteContainertask).ParamsSpec().Rule(),
	},
	"deletecrawler": Definition{
		Action: "delete",
		Entity: "crawler",
		API:    "glue",
		Params: new(DeleteCrawler).ParamsSpec().Rule(),
	},
	"deletedatabase": Definition{
		Action: "delete",
		Entity: "database",
		API:    "rds",
		Params: new(DeleteDatabase).ParamsSpec().Rule(),
	},
	"deletedbsubnetgroup": Definition{
		Action: "delete",
		Entity: "dbsubnetgroup",
		API:    "rds",
		Params: new(DeleteDbsubnetgroup).ParamsSpec().Rule(),
	},
	"deletedeployapplication": Definition{
		Action: "delete",
		Entity: "deployapplication",
		API:    "codedeploy",
		Params: new(DeleteDeployapplication).ParamsSpec().Rule(),
	},
	"deletedeploymentgroup": Definition{
		Action: "delete",
		Entity: "deploymentgroup",
		API:    "codedeploy",
		Params: new(DeleteDeploymentgroup).ParamsSpec().Rule(),
	},
	"deletedistribution": Definition{
		Action: "delete",
		Entity: "distribution",
		API:    "cloudfront",
		Params: new(DeleteDistribution).ParamsSpec().Rule(),
	},
	"deletedynamodbtable": Definition{
		Action: "delete",
		Entity: "dynamodbtable",
		API:    "dynamodb",
		Params: new(DeleteDynamodbtable).ParamsSpec().Rule(),
	},
	"deleteekscluster": Definition{
		Action: "delete",
		Entity: "ekscluster",
		API:    "eks",
		Params: new(DeleteEkscluster).ParamsSpec().Rule(),
	},
	"deleteeksnodegroup": Definition{
		Action: "delete",
		Entity: "eksnodegroup",
		API:    "eks",
		Params: new(DeleteEksnodegroup).ParamsSpec().Rule(),
	},
	"deleteelasticip": Definition{
		Action: "delete",
		Entity: "elasticip",
		API:    "ec2",
		Params: new(DeleteElasticip).ParamsSpec().Rule(),
	},
	"deleteemailidentity": Definition{
		Action: "delete",
		Entity: "emailidentity",
		API:    "sesv2",
		Params: new(DeleteEmailidentity).ParamsSpec().Rule(),
	},
	"deleteenvironment": Definition{
		Action: "delete",
		Entity: "environment",
		API:    "elasticbeanstalk",
		Params: new(DeleteEnvironment).ParamsSpec().Rule(),
	},
	"deleteeventbus": Definition{
		Action: "delete",
		Entity: "eventbus",
		API:    "eventbridge",
		Params: new(DeleteEventbus).ParamsSpec().Rule(),
	},
	"deleteeventrule": Definition{
		Action: "delete",
		Entity: "eventrule",
		API:    "eventbridge",
		Params: new(DeleteEventrule).ParamsSpec().Rule(),
	},
	"deletefilesystem": Definition{
		Action: "delete",
		Entity: "filesystem",
		API:    "efs",
		Params: new(DeleteFilesystem).ParamsSpec().Rule(),
	},
	"deletefsxbackup": Definition{
		Action: "delete",
		Entity: "fsxbackup",
		API:    "fsx",
		Params: new(DeleteFsxbackup).ParamsSpec().Rule(),
	},
	"deletefsxfilesystem": Definition{
		Action: "delete",
		Entity: "fsxfilesystem",
		API:    "fsx",
		Params: new(DeleteFsxfilesystem).ParamsSpec().Rule(),
	},
	"deletefunction": Definition{
		Action: "delete",
		Entity: "function",
		API:    "lambda",
		Params: new(DeleteFunction).ParamsSpec().Rule(),
	},
	"deletegluedatabase": Definition{
		Action: "delete",
		Entity: "gluedatabase",
		API:    "glue",
		Params: new(DeleteGluedatabase).ParamsSpec().Rule(),
	},
	"deletegroup": Definition{
		Action: "delete",
		Entity: "group",
		API:    "iam",
		Params: new(DeleteGroup).ParamsSpec().Rule(),
	},
	"deleteidentitypool": Definition{
		Action: "delete",
		Entity: "identitypool",
		API:    "cognitoidentity",
		Params: new(DeleteIdentitypool).ParamsSpec().Rule(),
	},
	"deleteimage": Definition{
		Action: "delete",
		Entity: "image",
		API:    "ec2",
		Params: new(DeleteImage).ParamsSpec().Rule(),
	},
	"deleteinstance": Definition{
		Action: "delete",
		Entity: "instance",
		API:    "ec2",
		Params: new(DeleteInstance).ParamsSpec().Rule(),
	},
	"deleteinstanceprofile": Definition{
		Action: "delete",
		Entity: "instanceprofile",
		API:    "iam",
		Params: new(DeleteInstanceprofile).ParamsSpec().Rule(),
	},
	"deleteinternetgateway": Definition{
		Action: "delete",
		Entity: "internetgateway",
		API:    "ec2",
		Params: new(DeleteInternetgateway).ParamsSpec().Rule(),
	},
	"deleteipset": Definition{
		Action: "delete",
		Entity: "ipset",
		API:    "wafv2",
		Params: new(DeleteIpset).ParamsSpec().Rule(),
	},
	"deletejob": Definition{
		Action: "delete",
		Entity: "job",
		API:    "glue",
		Params: new(DeleteJob).ParamsSpec().Rule(),
	},
	"deletekafkacluster": Definition{
		Action: "delete",
		Entity: "kafkacluster",
		API:    "kafka",
		Params: new(DeleteKafkacluster).ParamsSpec().Rule(),
	},
	"deletekeypair": Definition{
		Action: "delete",
		Entity: "keypair",
		API:    "ec2",
		Params: new(DeleteKeypair).ParamsSpec().Rule(),
	},
	"deletelaunchconfiguration": Definition{
		Action: "delete",
		Entity: "launchconfiguration",
		API:    "autoscaling",
		Params: new(DeleteLaunchconfiguration).ParamsSpec().Rule(),
	},
	"deletelistener": Definition{
		Action: "delete",
		Entity: "listener",
		API:    "elbv2",
		Params: new(DeleteListener).ParamsSpec().Rule(),
	},
	"deleteloadbalancer": Definition{
		Action: "delete",
		Entity: "loadbalancer",
		API:    "elbv2",
		Params: new(DeleteLoadbalancer).ParamsSpec().Rule(),
	},
	"deleteloggroup": Definition{
		Action: "delete",
		Entity: "loggroup",
		API:    "cloudwatchlogs",
		Params: new(DeleteLoggroup).ParamsSpec().Rule(),
	},
	"deleteloginprofile": Definition{
		Action: "delete",
		Entity: "loginprofile",
		API:    "iam",
		Params: new(DeleteLoginprofile).ParamsSpec().Rule(),
	},
	"deletemfadevice": Definition{
		Action: "delete",
		Entity: "mfadevice",
		API:    "iam",
		Params: new(DeleteMfadevice).ParamsSpec().Rule(),
	},
	"deletenatgateway": Definition{
		Action: "delete",
		Entity: "natgateway",
		API:    "ec2",
		Params: new(DeleteNatgateway).ParamsSpec().Rule(),
	},
	"deletenetworkinterface": Definition{
		Action: "delete",
		Entity: "networkinterface",
		API:    "ec2",
		Params: new(DeleteNetworkinterface).ParamsSpec().Rule(),
	},
	"deletepipeline": Definition{
		Action: "delete",
		Entity: "pipeline",
		API:    "codepipeline",
		Params: new(DeletePipeline).ParamsSpec().Rule(),
	},
	"deletepolicy": Definition{
		Action: "delete",
		Entity: "policy",
		API:    "iam",
		Params: new(DeletePolicy).ParamsSpec().Rule(),
	},
	"deletequeue": Definition{
		Action: "delete",
		Entity: "queue",
		API:    "sqs",
		Params: new(DeleteQueue).ParamsSpec().Rule(),
	},
	"deleterecord": Definition{
		Action: "delete",
		Entity: "record",
		API:    "route53",
		Params: new(DeleteRecord).ParamsSpec().Rule(),
	},
	"deleteredshiftcluster": Definition{
		Action: "delete",
		Entity: "redshiftcluster",
		API:    "redshift",
		Params: new(DeleteRedshiftcluster).ParamsSpec().Rule(),
	},
	"deleteredshiftsubnetgroup": Definition{
		Action: "delete",
		Entity: "redshiftsubnetgroup",
		API:    "redshift",
		Params: new(DeleteRedshiftsubnetgroup).ParamsSpec().Rule(),
	},
	"deletereplicationgroup": Definition{
		Action: "delete",
		Entity: "replicationgroup",
		API:    "elasticache",
		Params: new(DeleteReplicationgroup).ParamsSpec().Rule(),
	},
	"deleterepository": Definition{
		Action: "delete",
		Entity: "repository",
		API:    "ecr",
		Params: new(DeleteRepository).ParamsSpec().Rule(),
	},
	"deleterole": Definition{
		Action: "delete",
		Entity: "role",
		API:    "iam",
		Params: new(DeleteRole).ParamsSpec().Rule(),
	},
	"deleteroute": Definition{
		Action: "delete",
		Entity: "route",
		API:    "ec2",
		Params: new(DeleteRoute).ParamsSpec().Rule(),
	},
	"deleteroutetable": Definition{
		Action: "delete",
		Entity: "routetable",
		API:    "ec2",
		Params: new(DeleteRoutetable).ParamsSpec().Rule(),
	},
	"deleterulegroup": Definition{
		Action: "delete",
		Entity: "rulegroup",
		API:    "wafv2",
		Params: new(DeleteRulegroup).ParamsSpec().Rule(),
	},
	"deletes3object": Definition{
		Action: "delete",
		Entity: "s3object",
		API:    "s3",
		Params: new(DeleteS3object).ParamsSpec().Rule(),
	},
	"deletescalinggroup": Definition{
		Action: "delete",
		Entity: "scalinggroup",
		API:    "autoscaling",
		Params: new(DeleteScalinggroup).ParamsSpec().Rule(),
	},
	"deletescalingpolicy": Definition{
		Action: "delete",
		Entity: "scalingpolicy",
		API:    "autoscaling",
		Params: new(DeleteScalingpolicy).ParamsSpec().Rule(),
	},
	"deletesecret": Definition{
		Action: "delete",
		Entity: "secret",
		API:    "secretsmanager",
		Params: new(DeleteSecret).ParamsSpec().Rule(),
	},
	"deletesecuritygroup": Definition{
		Action: "delete",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(DeleteSecuritygroup).ParamsSpec().Rule(),
	},
	"deletesnapshot": Definition{
		Action: "delete",
		Entity: "snapshot",
		API:    "ec2",
		Params: new(DeleteSnapshot).ParamsSpec().Rule(),
	},
	"deletessmparameter": Definition{
		Action: "delete",
		Entity: "ssmparameter",
		API:    "ssm",
		Params: new(DeleteSsmparameter).ParamsSpec().Rule(),
	},
	"deletestack": Definition{
		Action: "delete",
		Entity: "stack",
		API:    "cloudformation",
		Params: new(DeleteStack).ParamsSpec().Rule(),
	},
	"deletestatemachine": Definition{
		Action: "delete",
		Entity: "statemachine",
		API:    "sfn",
		Params: new(DeleteStatemachine).ParamsSpec().Rule(),
	},
	"deletestream": Definition{
		Action: "delete",
		Entity: "stream",
		API:    "kinesis",
		Params: new(DeleteStream).ParamsSpec().Rule(),
	},
	"deletesubnet": Definition{
		Action: "delete",
		Entity: "subnet",
		API:    "ec2",
		Params: new(DeleteSubnet).ParamsSpec().Rule(),
	},
	"deletesubscription": Definition{
		Action: "delete",
		Entity: "subscription",
		API:    "sns",
		Params: new(DeleteSubscription).ParamsSpec().Rule(),
	},
	"deletetag": Definition{
		Action: "delete",
		Entity: "tag",
		API:    "ec2",
		Params: new(DeleteTag).ParamsSpec().Rule(),
	},
	"deletetargetgroup": Definition{
		Action: "delete",
		Entity: "targetgroup",
		API:    "elbv2",
		Params: new(DeleteTargetgroup).ParamsSpec().Rule(),
	},
	"deletetopic": Definition{
		Action: "delete",
		Entity: "topic",
		API:    "sns",
		Params: new(DeleteTopic).ParamsSpec().Rule(),
	},
	"deletetrail": Definition{
		Action: "delete",
		Entity: "trail",
		API:    "cloudtrail",
		Params: new(DeleteTrail).ParamsSpec().Rule(),
	},
	"deletetransitgateway": Definition{
		Action: "delete",
		Entity: "transitgateway",
		API:    "ec2",
		Params: new(DeleteTransitgateway).ParamsSpec().Rule(),
	},
	"deletetransitgatewayattachment": Definition{
		Action: "delete",
		Entity: "transitgatewayattachment",
		API:    "ec2",
		Params: new(DeleteTransitgatewayattachment).ParamsSpec().Rule(),
	},
	"deletetransitgatewayroutetable": Definition{
		Action: "delete",
		Entity: "transitgatewayroutetable",
		API:    "ec2",
		Params: new(DeleteTransitgatewayroutetable).ParamsSpec().Rule(),
	},
	"deleteuser": Definition{
		Action: "delete",
		Entity: "user",
		API:    "iam",
		Params: new(DeleteUser).ParamsSpec().Rule(),
	},
	"deleteuserpool": Definition{
		Action: "delete",
		Entity: "userpool",
		API:    "cognitoidentityprovider",
		Params: new(DeleteUserpool).ParamsSpec().Rule(),
	},
	"deletevolume": Definition{
		Action: "delete",
		Entity: "volume",
		API:    "ec2",
		Params: new(DeleteVolume).ParamsSpec().Rule(),
	},
	"deletevpc": Definition{
		Action: "delete",
		Entity: "vpc",
		API:    "ec2",
		Params: new(DeleteVpc).ParamsSpec().Rule(),
	},
	"deletevpcendpoint": Definition{
		Action: "delete",
		Entity: "vpcendpoint",
		API:    "ec2",
		Params: new(DeleteVpcendpoint).ParamsSpec().Rule(),
	},
	"deletewebacl": Definition{
		Action: "delete",
		Entity: "webacl",
		API:    "wafv2",
		Params: new(DeleteWebacl).ParamsSpec().Rule(),
	},
	"deletezone": Definition{
		Action: "delete",
		Entity: "zone",
		API:    "route53",
		Params: new(DeleteZone).ParamsSpec().Rule(),
	},
	"detachalarm": Definition{
		Action: "detach",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(DetachAlarm).ParamsSpec().Rule(),
	},
	"detachclassicloadbalancer": Definition{
		Action: "detach",
		Entity: "classicloadbalancer",
		API:    "elb",
		Params: new(DetachClassicLoadbalancer).ParamsSpec().Rule(),
	},
	"detachcontainertask": Definition{
		Action: "detach",
		Entity: "containertask",
		API:    "ecs",
		Params: new(DetachContainertask).ParamsSpec().Rule(),
	},
	"detachelasticip": Definition{
		Action: "detach",
		Entity: "elasticip",
		API:    "ec2",
		Params: new(DetachElasticip).ParamsSpec().Rule(),
	},
	"detacheventtarget": Definition{
		Action: "detach",
		Entity: "eventtarget",
		API:    "eventbridge",
		Params: new(DetachEventtarget).ParamsSpec().Rule(),
	},
	"detachinstance": Definition{
		Action: "detach",
		Entity: "instance",
		API:    "elbv2",
		Params: new(DetachInstance).ParamsSpec().Rule(),
	},
	"detachinstanceprofile": Definition{
		Action: "detach",
		Entity: "instanceprofile",
		API:    "ec2",
		Params: new(DetachInstanceprofile).ParamsSpec().Rule(),
	},
	"detachinternetgateway": Definition{
		Action: "detach",
		Entity: "internetgateway",
		API:    "ec2",
		Params: new(DetachInternetgateway).ParamsSpec().Rule(),
	},
	"detachmfadevice": Definition{
		Action: "detach",
		Entity: "mfadevice",
		API:    "iam",
		Params: new(DetachMfadevice).ParamsSpec().Rule(),
	},
	"detachnetworkinterface": Definition{
		Action: "detach",
		Entity: "networkinterface",
		API:    "ec2",
		Params: new(DetachNetworkinterface).ParamsSpec().Rule(),
	},
	"detachpolicy": Definition{
		Action: "detach",
		Entity: "policy",
		API:    "iam",
		Params: new(DetachPolicy).ParamsSpec().Rule(),
	},
	"detachrole": Definition{
		Action: "detach",
		Entity: "role",
		API:    "iam",
		Params: new(DetachRole).ParamsSpec().Rule(),
	},
	"detachroutetable": Definition{
		Action: "detach",
		Entity: "routetable",
		API:    "ec2",
		Params: new(DetachRoutetable).ParamsSpec().Rule(),
	},
	"detachsecuritygroup": Definition{
		Action: "detach",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(DetachSecuritygroup).ParamsSpec().Rule(),
	},
	"detachuser": Definition{
		Action: "detach",
		Entity: "user",
		API:    "iam",
		Params: new(DetachUser).ParamsSpec().Rule(),
	},
	"detachvolume": Definition{
		Action: "detach",
		Entity: "volume",
		API:    "ec2",
		Params: new(DetachVolume).ParamsSpec().Rule(),
	},
	"importimage": Definition{
		Action: "import",
		Entity: "image",
		API:    "ec2",
		Params: new(ImportImage).ParamsSpec().Rule(),
	},
	"restartdatabase": Definition{
		Action: "restart",
		Entity: "database",
		API:    "rds",
		Params: new(RestartDatabase).ParamsSpec().Rule(),
	},
	"restartinstance": Definition{
		Action: "restart",
		Entity: "instance",
		API:    "ec2",
		Params: new(RestartInstance).ParamsSpec().Rule(),
	},
	"startalarm": Definition{
		Action: "start",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(StartAlarm).ParamsSpec().Rule(),
	},
	"startbuildproject": Definition{
		Action: "start",
		Entity: "buildproject",
		API:    "codebuild",
		Params: new(StartBuildproject).ParamsSpec().Rule(),
	},
	"startcontainertask": Definition{
		Action: "start",
		Entity: "containertask",
		API:    "ecs",
		Params: new(StartContainertask).ParamsSpec().Rule(),
	},
	"startcrawler": Definition{
		Action: "start",
		Entity: "crawler",
		API:    "glue",
		Params: new(StartCrawler).ParamsSpec().Rule(),
	},
	"startdatabase": Definition{
		Action: "start",
		Entity: "database",
		API:    "rds",
		Params: new(StartDatabase).ParamsSpec().Rule(),
	},
	"starteventrule": Definition{
		Action: "start",
		Entity: "eventrule",
		API:    "eventbridge",
		Params: new(StartEventrule).ParamsSpec().Rule(),
	},
	"startexecution": Definition{
		Action: "start",
		Entity: "execution",
		API:    "sfn",
		Params: new(StartExecution).ParamsSpec().Rule(),
	},
	"startinstance": Definition{
		Action: "start",
		Entity: "instance",
		API:    "ec2",
		Params: new(StartInstance).ParamsSpec().Rule(),
	},
	"startjob": Definition{
		Action: "start",
		Entity: "job",
		API:    "glue",
		Params: new(StartJob).ParamsSpec().Rule(),
	},
	"startpipeline": Definition{
		Action: "start",
		Entity: "pipeline",
		API:    "codepipeline",
		Params: new(StartPipeline).ParamsSpec().Rule(),
	},
	"starttrail": Definition{
		Action: "start",
		Entity: "trail",
		API:    "cloudtrail",
		Params: new(StartTrail).ParamsSpec().Rule(),
	},
	"stopalarm": Definition{
		Action: "stop",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(StopAlarm).ParamsSpec().Rule(),
	},
	"stopbuildproject": Definition{
		Action: "stop",
		Entity: "buildproject",
		API:    "codebuild",
		Params: new(StopBuildproject).ParamsSpec().Rule(),
	},
	"stopcontainertask": Definition{
		Action: "stop",
		Entity: "containertask",
		API:    "ecs",
		Params: new(StopContainertask).ParamsSpec().Rule(),
	},
	"stopcrawler": Definition{
		Action: "stop",
		Entity: "crawler",
		API:    "glue",
		Params: new(StopCrawler).ParamsSpec().Rule(),
	},
	"stopdatabase": Definition{
		Action: "stop",
		Entity: "database",
		API:    "rds",
		Params: new(StopDatabase).ParamsSpec().Rule(),
	},
	"stopdeployment": Definition{
		Action: "stop",
		Entity: "deployment",
		API:    "codedeploy",
		Params: new(StopDeployment).ParamsSpec().Rule(),
	},
	"stopeventrule": Definition{
		Action: "stop",
		Entity: "eventrule",
		API:    "eventbridge",
		Params: new(StopEventrule).ParamsSpec().Rule(),
	},
	"stopexecution": Definition{
		Action: "stop",
		Entity: "execution",
		API:    "sfn",
		Params: new(StopExecution).ParamsSpec().Rule(),
	},
	"stopinstance": Definition{
		Action: "stop",
		Entity: "instance",
		API:    "ec2",
		Params: new(StopInstance).ParamsSpec().Rule(),
	},
	"stoppipeline": Definition{
		Action: "stop",
		Entity: "pipeline",
		API:    "codepipeline",
		Params: new(StopPipeline).ParamsSpec().Rule(),
	},
	"stoptrail": Definition{
		Action: "stop",
		Entity: "trail",
		API:    "cloudtrail",
		Params: new(StopTrail).ParamsSpec().Rule(),
	},
	"updateaccelerator": Definition{
		Action: "update",
		Entity: "accelerator",
		API:    "globalaccelerator",
		Params: new(UpdateAccelerator).ParamsSpec().Rule(),
	},
	"updateapplication": Definition{
		Action: "update",
		Entity: "application",
		API:    "elasticbeanstalk",
		Params: new(UpdateApplication).ParamsSpec().Rule(),
	},
	"updatebucket": Definition{
		Action: "update",
		Entity: "bucket",
		API:    "s3",
		Params: new(UpdateBucket).ParamsSpec().Rule(),
	},
	"updatebuildproject": Definition{
		Action: "update",
		Entity: "buildproject",
		API:    "codebuild",
		Params: new(UpdateBuildproject).ParamsSpec().Rule(),
	},
	"updatecachecluster": Definition{
		Action: "update",
		Entity: "cachecluster",
		API:    "elasticache",
		Params: new(UpdateCachecluster).ParamsSpec().Rule(),
	},
	"updatecachesubnetgroup": Definition{
		Action: "update",
		Entity: "cachesubnetgroup",
		API:    "elasticache",
		Params: new(UpdateCachesubnetgroup).ParamsSpec().Rule(),
	},
	"updateclassicloadbalancer": Definition{
		Action: "update",
		Entity: "classicloadbalancer",
		API:    "elb",
		Params: new(UpdateClassicLoadbalancer).ParamsSpec().Rule(),
	},
	"updateconfigrule": Definition{
		Action: "update",
		Entity: "configrule",
		API:    "configservice",
		Params: new(UpdateConfigrule).ParamsSpec().Rule(),
	},
	"updatecontainertask": Definition{
		Action: "update",
		Entity: "containertask",
		API:    "ecs",
		Params: new(UpdateContainertask).ParamsSpec().Rule(),
	},
	"updatedistribution": Definition{
		Action: "update",
		Entity: "distribution",
		API:    "cloudfront",
		Params: new(UpdateDistribution).ParamsSpec().Rule(),
	},
	"updateenvironment": Definition{
		Action: "update",
		Entity: "environment",
		API:    "elasticbeanstalk",
		Params: new(UpdateEnvironment).ParamsSpec().Rule(),
	},
	"updateeventrule": Definition{
		Action: "update",
		Entity: "eventrule",
		API:    "eventbridge",
		Params: new(UpdateEventrule).ParamsSpec().Rule(),
	},
	"updateimage": Definition{
		Action: "update",
		Entity: "image",
		API:    "ec2",
		Params: new(UpdateImage).ParamsSpec().Rule(),
	},
	"updateinstance": Definition{
		Action: "update",
		Entity: "instance",
		API:    "ec2",
		Params: new(UpdateInstance).ParamsSpec().Rule(),
	},
	"updateipset": Definition{
		Action: "update",
		Entity: "ipset",
		API:    "wafv2",
		Params: new(UpdateIpset).ParamsSpec().Rule(),
	},
	"updateloggroup": Definition{
		Action: "update",
		Entity: "loggroup",
		API:    "cloudwatchlogs",
		Params: new(UpdateLoggroup).ParamsSpec().Rule(),
	},
	"updateloginprofile": Definition{
		Action: "update",
		Entity: "loginprofile",
		API:    "iam",
		Params: new(UpdateLoginprofile).ParamsSpec().Rule(),
	},
	"updatepolicy": Definition{
		Action: "update",
		Entity: "policy",
		API:    "iam",
		Params: new(UpdatePolicy).ParamsSpec().Rule(),
	},
	"updaterecord": Definition{
		Action: "update",
		Entity: "record",
		API:    "route53",
		Params: new(UpdateRecord).ParamsSpec().Rule(),
	},
	"updateredshiftcluster": Definition{
		Action: "update",
		Entity: "redshiftcluster",
		API:    "redshift",
		Params: new(UpdateRedshiftcluster).ParamsSpec().Rule(),
	},
	"updates3object": Definition{
		Action: "update",
		Entity: "s3object",
		API:    "s3",
		Params: new(UpdateS3object).ParamsSpec().Rule(),
	},
	"updatescalinggroup": Definition{
		Action: "update",
		Entity: "scalinggroup",
		API:    "autoscaling",
		Params: new(UpdateScalinggroup).ParamsSpec().Rule(),
	},
	"updatesecret": Definition{
		Action: "update",
		Entity: "secret",
		API:    "secretsmanager",
		Params: new(UpdateSecret).ParamsSpec().Rule(),
	},
	"updatesecuritygroup": Definition{
		Action: "update",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(UpdateSecuritygroup).ParamsSpec().Rule(),
	},
	"updatessmparameter": Definition{
		Action: "update",
		Entity: "ssmparameter",
		API:    "ssm",
		Params: new(UpdateSsmparameter).ParamsSpec().Rule(),
	},
	"updatestack": Definition{
		Action: "update",
		Entity: "stack",
		API:    "cloudformation",
		Params: new(UpdateStack).ParamsSpec().Rule(),
	},
	"updatestatemachine": Definition{
		Action: "update",
		Entity: "statemachine",
		API:    "sfn",
		Params: new(UpdateStatemachine).ParamsSpec().Rule(),
	},
	"updatestream": Definition{
		Action: "update",
		Entity: "stream",
		API:    "kinesis",
		Params: new(UpdateStream).ParamsSpec().Rule(),
	},
	"updatesubnet": Definition{
		Action: "update",
		Entity: "subnet",
		API:    "ec2",
		Params: new(UpdateSubnet).ParamsSpec().Rule(),
	},
	"updatetargetgroup": Definition{
		Action: "update",
		Entity: "targetgroup",
		API:    "elbv2",
		Params: new(UpdateTargetgroup).ParamsSpec().Rule(),
	},
}

var DriverSupportedActions = map[string][]string{
	"attach":       []string{"alarm", "classicloadbalancer", "containertask", "elasticip", "eventtarget", "instance", "instanceprofile", "internetgateway", "listener", "mfadevice", "networkinterface", "policy", "role", "routetable", "securitygroup", "user", "volume"},
	"authenticate": []string{"registry"},
	"check":        []string{"certificate", "database", "distribution", "instance", "loadbalancer", "natgateway", "networkinterface", "scalinggroup", "securitygroup", "volume"},
	"copy":         []string{"image", "snapshot"},
	"create":       []string{"accelerator", "acceleratorlistener", "accesskey", "alarm", "apigateway", "apigatewayroute", "apigatewaystage", "application", "appscalingpolicy", "appscalingtarget", "broker", "bucket", "buildproject", "cachecluster", "cachesubnetgroup", "certificate", "classicloadbalancer", "configrule", "configurationset", "containercluster", "crawler", "database", "dbsubnetgroup", "deployapplication", "deployment", "deploymentgroup", "distribution", "dynamodbtable", "ekscluster", "eksnodegroup", "elasticip", "emailidentity", "environment", "eventbus", "eventrule", "filesystem", "fsxbackup", "fsxfilesystem", "function", "gluedatabase", "group", "identitypool", "image", "instance", "instanceprofile", "internetgateway", "ipset", "job", "kafkacluster", "keypair", "launchconfiguration", "listener", "loadbalancer", "loggroup", "loginprofile", "mfadevice", "natgateway", "networkinterface", "pipeline", "policy", "queue", "record", "redshiftcluster", "redshiftsubnetgroup", "replicationgroup", "repository", "role", "route", "routetable", "rulegroup", "s3object", "scalinggroup", "scalingpolicy", "secret", "securitygroup", "snapshot", "ssmparameter", "stack", "statemachine", "stream", "subnet", "subscription", "tag", "targetgroup", "topic", "trail", "transitgateway", "transitgatewayattachment", "transitgatewayroutetable", "user", "userpool", "volume", "vpc", "vpcendpoint", "webacl", "zone"},
	"delete":       []string{"accelerator", "acceleratorlistener", "accesskey", "alarm", "apigateway", "apigatewayroute", "apigatewaystage", "application", "appscalingpolicy", "appscalingtarget", "broker", "bucket", "buildproject", "cachecluster", "cachesubnetgroup", "certificate", "classicloadbalancer", "configrule", "configurationset", "containercluster", "containertask", "crawler", "database", "dbsubnetgroup", "deployapplication", "deploymentgroup", "distribution", "dynamodbtable", "ekscluster", "eksnodegroup", "elasticip", "emailidentity", "environment", "eventbus", "eventrule", "filesystem", "fsxbackup", "fsxfilesystem", "function", "gluedatabase", "group", "identitypool", "image", "instance", "instanceprofile", "internetgateway", "ipset", "job", "kafkacluster", "keypair", "launchconfiguration", "listener", "loadbalancer", "loggroup", "loginprofile", "mfadevice", "natgateway", "networkinterface", "pipeline", "policy", "queue", "record", "redshiftcluster", "redshiftsubnetgroup", "replicationgroup", "repository", "role", "route", "routetable", "rulegroup", "s3object", "scalinggroup", "scalingpolicy", "secret", "securitygroup", "snapshot", "ssmparameter", "stack", "statemachine", "stream", "subnet", "subscription", "tag", "targetgroup", "topic", "trail", "transitgateway", "transitgatewayattachment", "transitgatewayroutetable", "user", "userpool", "volume", "vpc", "vpcendpoint", "webacl", "zone"},
	"detach":       []string{"alarm", "classicloadbalancer", "containertask", "elasticip", "eventtarget", "instance", "instanceprofile", "internetgateway", "mfadevice", "networkinterface", "policy", "role", "routetable", "securitygroup", "user", "volume"},
	"import":       []string{"image"},
	"restart":      []string{"database", "instance"},
	"start":        []string{"alarm", "buildproject", "containertask", "crawler", "database", "eventrule", "execution", "instance", "job", "pipeline", "trail"},
	"stop":         []string{"alarm", "buildproject", "containertask", "crawler", "database", "deployment", "eventrule", "execution", "instance", "pipeline", "trail"},
	"update":       []string{"accelerator", "application", "bucket", "buildproject", "cachecluster", "cachesubnetgroup", "classicloadbalancer", "configrule", "containertask", "distribution", "environment", "eventrule", "image", "instance", "ipset", "loggroup", "loginprofile", "policy", "record", "redshiftcluster", "s3object", "scalinggroup", "secret", "securitygroup", "ssmparameter", "stack", "statemachine", "stream", "subnet", "targetgroup"},
}
