/* Copyright 2017 WALLIX

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// DO NOT EDIT
// This file was automatically generated with go generate
package awsspec

var APIPerTemplateDefName = map[string]string{
	"attachalarm":               "cloudwatch",
	"attachclassicloadbalancer": "elb",
	"attachcontainertask":       "ecs",
	"attachelasticip":           "ec2",
	"attachinstance":            "elbv2",
	"attachinstanceprofile":     "ec2",
	"attachinternetgateway":     "ec2",
	"attachlistener":            "elbv2",
	"attachmfadevice":           "iam",
	"attachnetworkinterface":    "ec2",
	"attachpolicy":              "iam",
	"attachrole":                "iam",
	"attachroutetable":          "ec2",
	"attachsecuritygroup":       "ec2",
	"attachuser":                "iam",
	"attachvolume":              "ec2",
	"authenticateregistry":      "ecr",
	"checkcertificate":          "acm",
	"checkdatabase":             "rds",
	"checkdistribution":         "cloudfront",
	"checkinstance":             "ec2",
	"checkloadbalancer":         "elbv2",
	"checknatgateway":           "ec2",
	"checknetworkinterface":     "ec2",
	"checkscalinggroup":         "autoscaling",
	"checksecuritygroup":        "ec2",
	"checkvolume":               "ec2",
	"copyimage":                 "ec2",
	"copysnapshot":              "ec2",
	"createaccesskey":           "iam",
	"createalarm":               "cloudwatch",
	"createapigateway":          "apigatewayv2",
	"createapigatewayroute":     "apigatewayv2",
	"createapigatewaystage":     "apigatewayv2",
	"createappscalingpolicy":    "applicationautoscaling",
	"createappscalingtarget":    "applicationautoscaling",
	"createbucket":              "s3",
	"createcertificate":         "acm",
	"createclassicloadbalancer": "elb",
	"createcontainercluster":    "ecs",
	"createdatabase":            "rds",
	"createdbsubnetgroup":       "rds",
	"createdistribution":        "cloudfront",
	"createdynamodbtable":       "dynamodb",
	"createekscluster":          "eks",
	"createeksnodegroup":        "eks",
	"createelasticip":           "ec2",
	"createfilesystem":          "efs",
	"createfunction":            "lambda",
	"creategroup":               "iam",
	"createimage":               "ec2",
	"createinstance":            "ec2",
	"createinstanceprofile":     "iam",
	"createinternetgateway":     "ec2",
	"createkeypair":             "ec2",
	"createlaunchconfiguration": "autoscaling",
	"createlistener":            "elbv2",
	"createloadbalancer":        "elbv2",
	"createloggroup":            "cloudwatchlogs",
	"createloginprofile":        "iam",
	"createmfadevice":           "iam",
	"createnatgateway":          "ec2",
	"createnetworkinterface":    "ec2",
	"createpolicy":              "iam",
	"createqueue":               "sqs",
	"createrecord":              "route53",
	"createrepository":          "ecr",
	"createrole":                "iam",
	"createroute":               "ec2",
	"createroutetable":          "ec2",
	"creates3object":            "s3",
	"createscalinggroup":        "autoscaling",
	"createscalingpolicy":       "autoscaling",
	"createsecret":              "secretsmanager",
	"createsecuritygroup":       "ec2",
	"createsnapshot":            "ec2",
	"createssmparameter":        "ssm",
	"createstack":               "cloudformation",
	"createsubnet":              "ec2",
	"createsubscription":        "sns",
	"createtag":                 "ec2",
	"createtargetgroup":         "elbv2",
	"createtopic":               "sns",
	"createtrail":               "cloudtrail",
	"createuser":                "iam",
	"createvolume":              "ec2",
	"createvpc":                 "ec2",
	"createzone":                "route53",
	"deleteaccesskey":           "iam",
	"deletealarm":               "cloudwatch",
	"deleteapigateway":          "apigatewayv2",
	"deleteapigatewayroute":     "apigatewayv2",
	"deleteapigatewaystage":     "apigatewayv2",
	"deleteappscalingpolicy":    "applicationautoscaling",
	"deleteappscalingtarget":    "applicationautoscaling",
	"deletebucket":              "s3",
	"deletecertificate":         "acm",
	"deleteclassicloadbalancer": "elb",
	"deletecontainercluster":    "ecs",
	"deletecontainertask":       "ecs",
	"deletedatabase":            "rds",
	"deletedbsubnetgroup":       "rds",
	"deletedistribution":        "cloudfront",
	"deletedynamodbtable":       "dynamodb",
	"deleteekscluster":          "eks",
	"deleteeksnodegroup":        "eks",
	"deleteelasticip":           "ec2",
	"deletefilesystem":          "efs",
	"deletefunction":            "lambda",
	"deletegroup":               "iam",
	"deleteimage":               "ec2",
	"deleteinstance":            "ec2",
	"deleteinstanceprofile":     "iam",
	"deleteinternetgateway":     "ec2",
	"deletekeypair":             "ec2",
	"deletelaunchconfiguration": "autoscaling",
	"deletelistener":            "elbv2",
	"deleteloadbalancer":        "elbv2",
	"deleteloggroup":            "cloudwatchlogs",
	"deleteloginprofile":        "iam",
	"deletemfadevice":           "iam",
	"deletenatgateway":          "ec2",
	"deletenetworkinterface":    "ec2",
	"deletepolicy":              "iam",
	"deletequeue":               "sqs",
	"deleterecord":              "route53",
	"deleterepository":          "ecr",
	"deleterole":                "iam",
	"deleteroute":               "ec2",
	"deleteroutetable":          "ec2",
	"deletes3object":            "s3",
	"deletescalinggroup":        "autoscaling",
	"deletescalingpolicy":       "autoscaling",
	"deletesecret":              "secretsmanager",
	"deletesecuritygroup":       "ec2",
	"deletesnapshot":            "ec2",
	"deletessmparameter":        "ssm",
	"deletestack":               "cloudformation",
	"deletesubnet":              "ec2",
	"deletesubscription":        "sns",
	"deletetag":                 "ec2",
	"deletetargetgroup":         "elbv2",
	"deletetopic":               "sns",
	"deletetrail":               "cloudtrail",
	"deleteuser":                "iam",
	"deletevolume":              "ec2",
	"deletevpc":                 "ec2",
	"deletezone":                "route53",
	"detachalarm":               "cloudwatch",
	"detachclassicloadbalancer": "elb",
	"detachcontainertask":       "ecs",
	"detachelasticip":           "ec2",
	"detachinstance":            "elbv2",
	"detachinstanceprofile":     "ec2",
	"detachinternetgateway":     "ec2",
	"detachmfadevice":           "iam",
	"detachnetworkinterface":    "ec2",
	"detachpolicy":              "iam",
	"detachrole":                "iam",
	"detachroutetable":          "ec2",
	"detachsecuritygroup":       "ec2",
	"detachuser":                "iam",
	"detachvolume":              "ec2",
	"importimage":               "ec2",
	"restartdatabase":           "rds",
	"restartinstance":           "ec2",
	"startalarm":                "cloudwatch",
	"startcontainertask":        "ecs",
	"startdatabase":             "rds",
	"startinstance":             "ec2",
	"starttrail":                "cloudtrail",
	"stopalarm":                 "cloudwatch",
	"stopcontainertask":         "ecs",
	"stopdatabase":              "rds",
	"stopinstance":              "ec2",
	"stoptrail":                 "cloudtrail",
	"updatebucket":              "s3",
	"updateclassicloadbalancer": "elb",
	"updatecontainertask":       "ecs",
	"updatedistribution":        "cloudfront",
	"updateimage":               "ec2",
	"updateinstance":            "ec2",
	"updateloggroup":            "cloudwatchlogs",
	"updateloginprofile":        "iam",
	"updatepolicy":              "iam",
	"updaterecord":              "route53",
	"updates3object":            "s3",
	"updatescalinggroup":        "autoscaling",
	"updatesecret":              "secretsmanager",
	"updatesecuritygroup":       "ec2",
	"updatessmparameter":        "ssm",
	"updatestack":               "cloudformation",
	"updatesubnet":              "ec2",
	"updatetargetgroup":         "elbv2",
}

var AWSTemplatesDefinitions = map[string]Definition{
	"attachalarm": Definition{
		Action: "attach",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(AttachAlarm).ParamsSpec().Rule(),
	},
	"attachclassicloadbalancer": Definition{
		Action: "attach",
		Entity: "classicloadbalancer",
		API:    "elb",
		Params: new(AttachClassicLoadbalancer).ParamsSpec().Rule(),
	},
	"attachcontainertask": Definition{
		Action: "attach",
		Entity: "containertask",
		API:    "ecs",
		Params: new(AttachContainertask).ParamsSpec().Rule(),
	},
	"attachelasticip": Definition{
		Action: "attach",
		Entity: "elasticip",
		API:    "ec2",
		Params: new(AttachElasticip).ParamsSpec().Rule(),
	},
	"attachinstance": Definition{
		Action: "attach",
		Entity: "instance",
		API:    "elbv2",
		Params: new(AttachInstance).ParamsSpec().Rule(),
	},
	"attachinstanceprofile": Definition{
		Action: "attach",
		Entity: "instanceprofile",
		API:    "ec2",
		Params: new(AttachInstanceprofile).ParamsSpec().Rule(),
	},
	"attachinternetgateway": Definition{
		Action: "attach",
		Entity: "internetgateway",
		API:    "ec2",
		Params: new(AttachInternetgateway).ParamsSpec().Rule(),
	},
	"attachlistener": Definition{
		Action: "attach",
		Entity: "listener",
		API:    "elbv2",
		Params: new(AttachListener).ParamsSpec().Rule(),
	},
	"attachmfadevice": Definition{
		Action: "attach",
		Entity: "mfadevice",
		API:    "iam",
		Params: new(AttachMfadevice).ParamsSpec().Rule(),
	},
	"attachnetworkinterface": Definition{
		Action: "attach",
		Entity: "networkinterface",
		API:    "ec2",
		Params: new(AttachNetworkinterface).ParamsSpec().Rule(),
	},
	"attachpolicy": Definition{
		Action: "attach",
		Entity: "policy",
		API:    "iam",
		Params: new(AttachPolicy).ParamsSpec().Rule(),
	},
	"attachrole": Definition{
		Action: "attach",
		Entity: "role",
		API:    "iam",
		Params: new(AttachRole).ParamsSpec().Rule(),
	},
	"attachroutetable": Definition{
		Action: "attach",
		Entity: "routetable",
		API:    "ec2",
		Params: new(AttachRoutetable).ParamsSpec().Rule(),
	},
	"attachsecuritygroup": Definition{
		Action: "attach",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(AttachSecuritygroup).ParamsSpec().Rule(),
	},
	"attachuser": Definition{
		Action: "attach",
		Entity: "user",
		API:    "iam",
		Params: new(AttachUser).ParamsSpec().Rule(),
	},
	"attachvolume": Definition{
		Action: "attach",
		Entity: "volume",
		API:    "ec2",
		Params: new(AttachVolume).ParamsSpec().Rule(),
	},
	"authenticateregistry": Definition{
		Action: "authenticate",
		Entity: "registry",
		API:    "ecr",
		Params: new(AuthenticateRegistry).ParamsSpec().Rule(),
	},
	"checkcertificate": Definition{
		Action: "check",
		Entity: "certificate",
		API:    "acm",
		Params: new(CheckCertificate).ParamsSpec().Rule(),
	},
	"checkdatabase": Definition{
		Action: "check",
		Entity: "database",
		API:    "rds",
		Params: new(CheckDatabase).ParamsSpec().Rule(),
	},
	"checkdistribution": Definition{
		Action: "check",
		Entity: "distribution",
		API:    "cloudfront",
		Params: new(CheckDistribution).ParamsSpec().Rule(),
	},
	"checkinstance": Definition{
		Action: "check",
		Entity: "instance",
		API:    "ec2",
		Params: new(CheckInstance).ParamsSpec().Rule(),
	},
	"checkloadbalancer": Definition{
		Action: "check",
		Entity: "loadbalancer",
		API:    "elbv2",
		Params: new(CheckLoadbalancer).ParamsSpec().Rule(),
	},
	"checknatgateway": Definition{
		Action: "check",
		Entity: "natgateway",
		API:    "ec2",
		Params: new(CheckNatgateway).ParamsSpec().Rule(),
	},
	"checknetworkinterface": Definition{
		Action: "check",
		Entity: "networkinterface",
		API:    "ec2",
		Params: new(CheckNetworkinterface).ParamsSpec().Rule(),
	},
	"checkscalinggroup": Definition{
		Action: "check",
		Entity: "scalinggroup",
		API:    "autoscaling",
		Params: new(CheckScalinggroup).ParamsSpec().Rule(),
	},
	"checksecuritygroup": Definition{
		Action: "check",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(CheckSecuritygroup).ParamsSpec().Rule(),
	},
	"checkvolume": Definition{
		Action: "check",
		Entity: "volume",
		API:    "ec2",
		Params: new(CheckVolume).ParamsSpec().Rule(),
	},
	"copyimage": Definition{
		Action: "copy",
		Entity: "image",
		API:    "ec2",
		Params: new(CopyImage).ParamsSpec().Rule(),
	},
	"copysnapshot": Definition{
		Action: "copy",
		Entity: "snapshot",
		API:    "ec2",
		Params: new(CopySnapshot).ParamsSpec().Rule(),
	},
	"createaccesskey": Definition{
		Action: "create",
		Entity: "accesskey",
		API:    "iam",
		Params: new(CreateAccesskey).ParamsSpec().Rule(),
	},
	"createalarm": Definition{
		Action: "create",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(CreateAlarm).ParamsSpec().Rule(),
	},
	"createapigateway": Definition{
		Action: "create",
		Entity: "apigateway",
		API:    "apigatewayv2",
		Params: new(CreateApigateway).ParamsSpec().Rule(),
	},
	"createapigatewayroute": Definition{
		Action: "create",
		Entity: "apigatewayroute",
		API:    "apigatewayv2",
		Params: new(CreateApigatewayroute).ParamsSpec().Rule(),
	},
	"createapigatewaystage": Definition{
		Action: "create",
		Entity: "apigatewaystage",
		API:    "apigatewayv2",
		Params: new(CreateApigatewaystage).ParamsSpec().Rule(),
	},
	"createappscalingpolicy": Definition{
		Action: "create",
		Entity: "appscalingpolicy",
		API:    "applicationautoscaling",
		Params: new(CreateAppscalingpolicy).ParamsSpec().Rule(),
	},
	"createappscalingtarget": Definition{
		Action: "create",
		Entity: "appscalingtarget",
		API:    "applicationautoscaling",
		Params: new(CreateAppscalingtarget).ParamsSpec().Rule(),
	},
	"createbucket": Definition{
		Action: "create",
		Entity: "bucket",
		API:    "s3",
		Params: new(CreateBucket).ParamsSpec().Rule(),
	},
	"createcertificate": Definition{
		Action: "create",
		Entity: "certificate",
		API:    "acm",
		Params: new(CreateCertificate).ParamsSpec().Rule(),
	},
	"createclassicloadbalancer": Definition{
		Action: "create",
		Entity: "classicloadbalancer",
		API:    "elb",
		Params: new(CreateClassicLoadbalancer).ParamsSpec().Rule(),
	},
	"createcontainercluster": Definition{
		Action: "create",
		Entity: "containercluster",
		API:    "ecs",
		Params: new(CreateContainercluster).ParamsSpec().Rule(),
	},
	"createdatabase": Definition{
		Action: "create",
		Entity: "database",
		API:    "rds",
		Params: new(CreateDatabase).ParamsSpec().Rule(),
	},
	"createdbsubnetgroup": Definition{
		Action: "create",
		Entity: "dbsubnetgroup",
		API:    "rds",
		Params: new(CreateDbsubnetgroup).ParamsSpec().Rule(),
	},
	"createdistribution": Definition{
		Action: "create",
		Entity: "distribution",
		API:    "cloudfront",
		Params: new(CreateDistribution).ParamsSpec().Rule(),
	},
	"createdynamodbtable": Definition{
		Action: "create",
		Entity: "dynamodbtable",
		API:    "dynamodb",
		Params: new(CreateDynamodbtable).ParamsSpec().Rule(),
	},
	"createekscluster": Definition{
		Action: "create",
		Entity: "ekscluster",
		API:    "eks",
		Params: new(CreateEkscluster).ParamsSpec().Rule(),
	},
	"createeksnodegroup": Definition{
		Action: "create",
		Entity: "eksnodegroup",
		API:    "eks",
		Params: new(CreateEksnodegroup).ParamsSpec().Rule(),
	},
	"createelasticip": Definition{
		Action: "create",
		Entity: "elasticip",
		API:    "ec2",
		Params: new(CreateElasticip).ParamsSpec().Rule(),
	},
	"createfilesystem": Definition{
		Action: "create",
		Entity: "filesystem",
		API:    "efs",
		Params: new(CreateFilesystem).ParamsSpec().Rule(),
	},
	"createfunction": Definition{
		Action: "create",
		Entity: "function",
		API:    "lambda",
		Params: new(CreateFunction).ParamsSpec().Rule(),
	},
	"creategroup": Definition{
		Action: "create",
		Entity: "group",
		API:    "iam",
		Params: new(CreateGroup).ParamsSpec().Rule(),
	},
	"createimage": Definition{
		Action: "create",
		Entity: "image",
		API:    "ec2",
		Params: new(CreateImage).ParamsSpec().Rule(),
	},
	"createinstance": Definition{
		Action: "create",
		Entity: "instance",
		API:    "ec2",
		Params: new(CreateInstance).ParamsSpec().Rule(),
	},
	"createinstanceprofile": Definition{
		Action: "create",
		Entity: "instanceprofile",
		API:    "iam",
		Params: new(CreateInstanceprofile).ParamsSpec().Rule(),
	},
	"createinternetgateway": Definition{
		Action: "create",
		Entity: "internetgateway",
		API:    "ec2",
		Params: new(CreateInternetgateway).ParamsSpec().Rule(),
	},
	"createkeypair": Definition{
		Action: "create",
		Entity: "keypair",
		API:    "ec2",
		Params: new(CreateKeypair).ParamsSpec().Rule(),
	},
	"createlaunchconfiguration": Definition{
		Action: "create",
		Entity: "launchconfiguration",
		API:    "autoscaling",
		Params: new(CreateLaunchconfiguration).ParamsSpec().Rule(),
	},
	"createlistener": Definition{
		Action: "create",
		Entity: "listener",
		API:    "elbv2",
		Params: new(CreateListener).ParamsSpec().Rule(),
	},
	"createloadbalancer": Definition{
		Action: "create",
		Entity: "loadbalancer",
		API:    "elbv2",
		Params: new(CreateLoadbalancer).ParamsSpec().Rule(),
	},
	"createloggroup": Definition{
		Action: "create",
		Entity: "loggroup",
		API:    "cloudwatchlogs",
		Params: new(CreateLoggroup).ParamsSpec().Rule(),
	},
	"createloginprofile": Definition{
		Action: "create",
		Entity: "loginprofile",
		API:    "iam",
		Params: new(CreateLoginprofile).ParamsSpec().Rule(),
	},
	"createmfadevice": Definition{
		Action: "create",
		Entity: "mfadevice",
		API:    "iam",
		Params: new(CreateMfadevice).ParamsSpec().Rule(),
	},
	"createnatgateway": Definition{
		Action: "create",
		Entity: "natgateway",
		API:    "ec2",
		Params: new(CreateNatgateway).ParamsSpec().Rule(),
	},
	"createnetworkinterface": Definition{
		Action: "create",
		Entity: "networkinterface",
		API:    "ec2",
		Params: new(CreateNetworkinterface).ParamsSpec().Rule(),
	},
	"createpolicy": Definition{
		Action: "create",
		Entity: "policy",
		API:    "iam",
		Params: new(CreatePolicy).ParamsSpec().Rule(),
	},
	"createqueue": Definition{
		Action: "create",
		Entity: "queue",
		API:    "sqs",
		Params: new(CreateQueue).ParamsSpec().Rule(),
	},
	"createrecord": Definition{
		Action: "create",
		Entity: "record",
		API:    "route53",
		Params: new(CreateRecord).ParamsSpec().Rule(),
	},
	"createrepository": Definition{
		Action: "create",
		Entity: "repository",
		API:    "ecr",
		Params: new(CreateRepository).ParamsSpec().Rule(),
	},
	"createrole": Definition{
		Action: "create",
		Entity: "role",
		API:    "iam",
		Params: new(CreateRole).ParamsSpec().Rule(),
	},
	"createroute": Definition{
		Action: "create",
		Entity: "route",
		API:    "ec2",
		Params: new(CreateRoute).ParamsSpec().Rule(),
	},
	"createroutetable": Definition{
		Action: "create",
		Entity: "routetable",
		API:    "ec2",
		Params: new(CreateRoutetable).ParamsSpec().Rule(),
	},
	"creates3object": Definition{
		Action: "create",
		Entity: "s3object",
		API:    "s3",
		Params: new(CreateS3object).ParamsSpec().Rule(),
	},
	"createscalinggroup": Definition{
		Action: "create",
		Entity: "scalinggroup",
		API:    "autoscaling",
		Params: new(CreateScalinggroup).ParamsSpec().Rule(),
	},
	"createscalingpolicy": Definition{
		Action: "create",
		Entity: "scalingpolicy",
		API:    "autoscaling",
		Params: new(CreateScalingpolicy).ParamsSpec().Rule(),
	},
	"createsecret": Definition{
		Action: "create",
		Entity: "secret",
		API:    "secretsmanager",
		Params: new(CreateSecret).ParamsSpec().Rule(),
	},
	"createsecuritygroup": Definition{
		Action: "create",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(CreateSecuritygroup).ParamsSpec().Rule(),
	},
	"createsnapshot": Definition{
		Action: "create",
		Entity: "snapshot",
		API:    "ec2",
		Params: new(CreateSnapshot).ParamsSpec().Rule(),
	},
	"createssmparameter": Definition{
		Action: "create",
		Entity: "ssmparameter",
		API:    "ssm",
		Params: new(CreateSsmparameter).ParamsSpec().Rule(),
	},
	"createstack": Definition{
		Action: "create",
		Entity: "stack",
		API:    "cloudformation",
		Params: new(CreateStack).ParamsSpec().Rule(),
	},
	"createsubnet": Definition{
		Action: "create",
		Entity: "subnet",
		API:    "ec2",
		Params: new(CreateSubnet).ParamsSpec().Rule(),
	},
	"createsubscription": Definition{
		Action: "create",
		Entity: "subscription",
		API:    "sns",
		Params: new(CreateSubscription).ParamsSpec().Rule(),
	},
	"createtag": Definition{
		Action: "create",
		Entity: "tag",
		API:    "ec2",
		Params: new(CreateTag).ParamsSpec().Rule(),
	},
	"createtargetgroup": Definition{
		Action: "create",
		Entity: "targetgroup",
		API:    "elbv2",
		Params: new(CreateTargetgroup).ParamsSpec().Rule(),
	},
	"createtopic": Definition{
		Action: "create",
		Entity: "topic",
		API:    "sns",
		Params: new(CreateTopic).ParamsSpec().Rule(),
	},
	"createtrail": Definition{
		Action: "create",
		Entity: "trail",
		API:    "cloudtrail",
		Params: new(CreateTrail).ParamsSpec().Rule(),
	},
	"createuser": Definition{
		Action: "create",
		Entity: "user",
		API:    "iam",
		Params: new(CreateUser).ParamsSpec().Rule(),
	},
	"createvolume": Definition{
		Action: "create",
		Entity: "volume",
		API:    "ec2",
		Params: new(CreateVolume).ParamsSpec().Rule(),
	},
	"createvpc": Definition{
		Action: "create",
		Entity: "vpc",
		API:    "ec2",
		Params: new(CreateVpc).ParamsSpec().Rule(),
	},
	"createzone": Definition{
		Action: "create",
		Entity: "zone",
		API:    "route53",
		Params: new(CreateZone).ParamsSpec().Rule(),
	},
	"deleteaccesskey": Definition{
		Action: "delete",
		Entity: "accesskey",
		API:    "iam",
		Params: new(DeleteAccesskey).ParamsSpec().Rule(),
	},
	"deletealarm": Definition{
		Action: "delete",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(DeleteAlarm).ParamsSpec().Rule(),
	},
	"deleteapigateway": Definition{
		Action: "delete",
		Entity: "apigateway",
		API:    "apigatewayv2",
		Params: new(DeleteApigateway).ParamsSpec().Rule(),
	},
	"deleteapigatewayroute": Definition{
		Action: "delete",
		Entity: "apigatewayroute",
		API:    "apigatewayv2",
		Params: new(DeleteApigatewayroute).ParamsSpec().Rule(),
	},
	"deleteapigatewaystage": Definition{
		Action: "delete",
		Entity: "apigatewaystage",
		API:    "apigatewayv2",
		Params: new(DeleteApigatewaystage).ParamsSpec().Rule(),
	},
	"deleteappscalingpolicy": Definition{
		Action: "delete",
		Entity: "appscalingpolicy",
		API:    "applicationautoscaling",
		Params: new(DeleteAppscalingpolicy).ParamsSpec().Rule(),
	},
	"deleteappscalingtarget": Definition{
		Action: "delete",
		Entity: "appscalingtarget",
		API:    "applicationautoscaling",
		Params: new(DeleteAppscalingtarget).ParamsSpec().Rule(),
	},
	"deletebucket": Definition{
		Action: "delete",
		Entity: "bucket",
		API:    "s3",
		Params: new(DeleteBucket).ParamsSpec().Rule(),
	},
	"deletecertificate": Definition{
		Action: "delete",
		Entity: "certificate",
		API:    "acm",
		Params: new(DeleteCertificate).ParamsSpec().Rule(),
	},
	"deleteclassicloadbalancer": Definition{
		Action: "delete",
		Entity: "classicloadbalancer",
		API:    "elb",
		Params: new(DeleteClassicLoadbalancer).ParamsSpec().Rule(),
	},
	"deletecontainercluster": Definition{
		Action: "delete",
		Entity: "containercluster",
		API:    "ecs",
		Params: new(DeleteContainercluster).ParamsSpec().Rule(),
	},
	"deletecontainertask": Definition{
		Action: "delete",
		Entity: "containertask",
		API:    "ecs",
		Params: new(DeleteContainertask).ParamsSpec().Rule(),
	},
	"deletedatabase": Definition{
		Action: "delete",
		Entity: "database",
		API:    "rds",
		Params: new(DeleteDatabase).ParamsSpec().Rule(),
	},
	"deletedbsubnetgroup": Definition{
		Action: "delete",
		Entity: "dbsubnetgroup",
		API:    "rds",
		Params: new(DeleteDbsubnetgroup).ParamsSpec().Rule(),
	},
	"deletedistribution": Definition{
		Action: "delete",
		Entity: "distribution",
		API:    "cloudfront",
		Params: new(DeleteDistribution).ParamsSpec().Rule(),
	},
	"deletedynamodbtable": Definition{
		Action: "delete",
		Entity: "dynamodbtable",
		API:    "dynamodb",
		Params: new(DeleteDynamodbtable).ParamsSpec().Rule(),
	},
	"deleteekscluster": Definition{
		Action: "delete",
		Entity: "ekscluster",
		API:    "eks",
		Params: new(DeleteEkscluster).ParamsSpec().Rule(),
	},
	"deleteeksnodegroup": Definition{
		Action: "delete",
		Entity: "eksnodegroup",
		API:    "eks",
		Params: new(DeleteEksnodegroup).ParamsSpec().Rule(),
	},
	"deleteelasticip": Definition{
		Action: "delete",
		Entity: "elasticip",
		API:    "ec2",
		Params: new(DeleteElasticip).ParamsSpec().Rule(),
	},
	"deletefilesystem": Definition{
		Action: "delete",
		Entity: "filesystem",
		API:    "efs",
		Params: new(DeleteFilesystem).ParamsSpec().Rule(),
	},
	"deletefunction": Definition{
		Action: "delete",
		Entity: "function",
		API:    "lambda",
		Params: new(DeleteFunction).ParamsSpec().Rule(),
	},
	"deletegroup": Definition{
		Action: "delete",
		Entity: "group",
		API:    "iam",
		Params: new(DeleteGroup).ParamsSpec().Rule(),
	},
	"deleteimage": Definition{
		Action: "delete",
		Entity: "image",
		API:    "ec2",
		Params: new(DeleteImage).ParamsSpec().Rule(),
	},
	"deleteinstance": Definition{
		Action: "delete",
		Entity: "instance",
		API:    "ec2",
		Params: new(DeleteInstance).ParamsSpec().Rule(),
	},
	"deleteinstanceprofile": Definition{
		Action: "delete",
		Entity: "instanceprofile",
		API:    "iam",
		Params: new(DeleteInstanceprofile).ParamsSpec().Rule(),
	},
	"deleteinternetgateway": Definition{
		Action: "delete",
		Entity: "internetgateway",
		API:    "ec2",
		Params: new(DeleteInternetgateway).ParamsSpec().Rule(),
	},
	"deletekeypair": Definition{
		Action: "delete",
		Entity: "keypair",
		API:    "ec2",
		Params: new(DeleteKeypair).ParamsSpec().Rule(),
	},
	"deletelaunchconfiguration": Definition{
		Action: "delete",
		Entity: "launchconfiguration",
		API:    "autoscaling",
		Params: new(DeleteLaunchconfiguration).ParamsSpec().Rule(),
	},
	"deletelistener": Definition{
		Action: "delete",
		Entity: "listener",
		API:    "elbv2",
		Params: new(DeleteListener).ParamsSpec().Rule(),
	},
	"deleteloadbalancer": Definition{
		Action: "delete",
		Entity: "loadbalancer",
		API:    "elbv2",
		Params: new(DeleteLoadbalancer).ParamsSpec().Rule(),
	},
	"deleteloggroup": Definition{
		Action: "delete",
		Entity: "loggroup",
		API:    "cloudwatchlogs",
		Params: new(DeleteLoggroup).ParamsSpec().Rule(),
	},
	"deleteloginprofile": Definition{
		Action: "delete",
		Entity: "loginprofile",
		API:    "iam",
		Params: new(DeleteLoginprofile).ParamsSpec().Rule(),
	},
	"deletemfadevice": Definition{
		Action: "delete",
		Entity: "mfadevice",
		API:    "iam",
		Params: new(DeleteMfadevice).ParamsSpec().Rule(),
	},
	"deletenatgateway": Definition{
		Action: "delete",
		Entity: "natgateway",
		API:    "ec2",
		Params: new(DeleteNatgateway).ParamsSpec().Rule(),
	},
	"deletenetworkinterface": Definition{
		Action: "delete",
		Entity: "networkinterface",
		API:    "ec2",
		Params: new(DeleteNetworkinterface).ParamsSpec().Rule(),
	},
	"deletepolicy": Definition{
		Action: "delete",
		Entity: "policy",
		API:    "iam",
		Params: new(DeletePolicy).ParamsSpec().Rule(),
	},
	"deletequeue": Definition{
		Action: "delete",
		Entity: "queue",
		API:    "sqs",
		Params: new(DeleteQueue).ParamsSpec().Rule(),
	},
	"deleterecord": Definition{
		Action: "delete",
		Entity: "record",
		API:    "route53",
		Params: new(DeleteRecord).ParamsSpec().Rule(),
	},
	"deleterepository": Definition{
		Action: "delete",
		Entity: "repository",
		API:    "ecr",
		Params: new(DeleteRepository).ParamsSpec().Rule(),
	},
	"deleterole": Definition{
		Action: "delete",
		Entity: "role",
		API:    "iam",
		Params: new(DeleteRole).ParamsSpec().Rule(),
	},
	"deleteroute": Definition{
		Action: "delete",
		Entity: "route",
		API:    "ec2",
		Params: new(DeleteRoute).ParamsSpec().Rule(),
	},
	"deleteroutetable": Definition{
		Action: "delete",
		Entity: "routetable",
		API:    "ec2",
		Params: new(DeleteRoutetable).ParamsSpec().Rule(),
	},
	"deletes3object": Definition{
		Action: "delete",
		Entity: "s3object",
		API:    "s3",
		Params: new(DeleteS3object).ParamsSpec().Rule(),
	},
	"deletescalinggroup": Definition{
		Action: "delete",
		Entity: "scalinggroup",
		API:    "autoscaling",
		Params: new(DeleteScalinggroup).ParamsSpec().Rule(),
	},
	"deletescalingpolicy": Definition{
		Action: "delete",
		Entity: "scalingpolicy",
		API:    "autoscaling",
		Params: new(DeleteScalingpolicy).ParamsSpec().Rule(),
	},
	"deletesecret": Definition{
		Action: "delete",
		Entity: "secret",
		API:    "secretsmanager",
		Params: new(DeleteSecret).ParamsSpec().Rule(),
	},
	"deletesecuritygroup": Definition{
		Action: "delete",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(DeleteSecuritygroup).ParamsSpec().Rule(),
	},
	"deletesnapshot": Definition{
		Action: "delete",
		Entity: "snapshot",
		API:    "ec2",
		Params: new(DeleteSnapshot).ParamsSpec().Rule(),
	},
	"deletessmparameter": Definition{
		Action: "delete",
		Entity: "ssmparameter",
		API:    "ssm",
		Params: new(DeleteSsmparameter).ParamsSpec().Rule(),
	},
	"deletestack": Definition{
		Action: "delete",
		Entity: "stack",
		API:    "cloudformation",
		Params: new(DeleteStack).ParamsSpec().Rule(),
	},
	"deletesubnet": Definition{
		Action: "delete",
		Entity: "subnet",
		API:    "ec2",
		Params: new(DeleteSubnet).ParamsSpec().Rule(),
	},
	"deletesubscription": Definition{
		Action: "delete",
		Entity: "subscription",
		API:    "sns",
		Params: new(DeleteSubscription).ParamsSpec().Rule(),
	},
	"deletetag": Definition{
		Action: "delete",
		Entity: "tag",
		API:    "ec2",
		Params: new(DeleteTag).ParamsSpec().Rule(),
	},
	"deletetargetgroup": Definition{
		Action: "delete",
		Entity: "targetgroup",
		API:    "elbv2",
		Params: new(DeleteTargetgroup).ParamsSpec().Rule(),
	},
	"deletetopic": Definition{
		Action: "delete",
		Entity: "topic",
		API:    "sns",
		Params: new(DeleteTopic).ParamsSpec().Rule(),
	},
	"deletetrail": Definition{
		Action: "delete",
		Entity: "trail",
		API:    "cloudtrail",
		Params: new(DeleteTrail).ParamsSpec().Rule(),
	},
	"deleteuser": Definition{
		Action: "delete",
		Entity: "user",
		API:    "iam",
		Params: new(DeleteUser).ParamsSpec().Rule(),
	},
	"deletevolume": Definition{
		Action: "delete",
		Entity: "volume",
		API:    "ec2",
		Params: new(DeleteVolume).ParamsSpec().Rule(),
	},
	"deletevpc": Definition{
		Action: "delete",
		Entity: "vpc",
		API:    "ec2",
		Params: new(DeleteVpc).ParamsSpec().Rule(),
	},
	"deletezone": Definition{
		Action: "delete",
		Entity: "zone",
		API:    "route53",
		Params: new(DeleteZone).ParamsSpec().Rule(),
	},
	"detachalarm": Definition{
		Action: "detach",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(DetachAlarm).ParamsSpec().Rule(),
	},
	"detachclassicloadbalancer": Definition{
		Action: "detach",
		Entity: "classicloadbalancer",
		API:    "elb",
		Params: new(DetachClassicLoadbalancer).ParamsSpec().Rule(),
	},
	"detachcontainertask": Definition{
		Action: "detach",
		Entity: "containertask",
		API:    "ecs",
		Params: new(DetachContainertask).ParamsSpec().Rule(),
	},
	"detachelasticip": Definition{
		Action: "detach",
		Entity: "elasticip",
		API:    "ec2",
		Params: new(DetachElasticip).ParamsSpec().Rule(),
	},
	"detachinstance": Definition{
		Action: "detach",
		Entity: "instance",
		API:    "elbv2",
		Params: new(DetachInstance).ParamsSpec().Rule(),
	},
	"detachinstanceprofile": Definition{
		Action: "detach",
		Entity: "instanceprofile",
		API:    "ec2",
		Params: new(DetachInstanceprofile).ParamsSpec().Rule(),
	},
	"detachinternetgateway": Definition{
		Action: "detach",
		Entity: "internetgateway",
		API:    "ec2",
		Params: new(DetachInternetgateway).ParamsSpec().Rule(),
	},
	"detachmfadevice": Definition{
		Action: "detach",
		Entity: "mfadevice",
		API:    "iam",
		Params: new(DetachMfadevice).ParamsSpec().Rule(),
	},
	"detachnetworkinterface": Definition{
		Action: "detach",
		Entity: "networkinterface",
		API:    "ec2",
		Params: new(DetachNetworkinterface).ParamsSpec().Rule(),
	},
	"detachpolicy": Definition{
		Action: "detach",
		Entity: "policy",
		API:    "iam",
		Params: new(DetachPolicy).ParamsSpec().Rule(),
	},
	"detachrole": Definition{
		Action: "detach",
		Entity: "role",
		API:    "iam",
		Params: new(DetachRole).ParamsSpec().Rule(),
	},
	"detachroutetable": Definition{
		Action: "detach",
		Entity: "routetable",
		API:    "ec2",
		Params: new(DetachRoutetable).ParamsSpec().Rule(),
	},
	"detachsecuritygroup": Definition{
		Action: "detach",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(DetachSecuritygroup).ParamsSpec().Rule(),
	},
	"detachuser": Definition{
		Action: "detach",
		Entity: "user",
		API:    "iam",
		Params: new(DetachUser).ParamsSpec().Rule(),
	},
	"detachvolume": Definition{
		Action: "detach",
		Entity: "volume",
		API:    "ec2",
		Params: new(DetachVolume).ParamsSpec().Rule(),
	},
	"importimage": Definition{
		Action: "import",
		Entity: "image",
		API:    "ec2",
		Params: new(ImportImage).ParamsSpec().Rule(),
	},
	"restartdatabase": Definition{
		Action: "restart",
		Entity: "database",
		API:    "rds",
		Params: new(RestartDatabase).ParamsSpec().Rule(),
	},
	"restartinstance": Definition{
		Action: "restart",
		Entity: "instance",
		API:    "ec2",
		Params: new(RestartInstance).ParamsSpec().Rule(),
	},
	"startalarm": Definition{
		Action: "start",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(StartAlarm).ParamsSpec().Rule(),
	},
	"startcontainertask": Definition{
		Action: "start",
		Entity: "containertask",
		API:    "ecs",
		Params: new(StartContainertask).ParamsSpec().Rule(),
	},
	"startdatabase": Definition{
		Action: "start",
		Entity: "database",
		API:    "rds",
		Params: new(StartDatabase).ParamsSpec().Rule(),
	},
	"startinstance": Definition{
		Action: "start",
		Entity: "instance",
		API:    "ec2",
		Params: new(StartInstance).ParamsSpec().Rule(),
	},
	"starttrail": Definition{
		Action: "start",
		Entity: "trail",
		API:    "cloudtrail",
		Params: new(StartTrail).ParamsSpec().Rule(),
	},
	"stopalarm": Definition{
		Action: "stop",
		Entity: "alarm",
		API:    "cloudwatch",
		Params: new(StopAlarm).ParamsSpec().Rule(),
	},
	"stopcontainertask": Definition{
		Action: "stop",
		Entity: "containertask",
		API:    "ecs",
		Params: new(StopContainertask).ParamsSpec().Rule(),
	},
	"stopdatabase": Definition{
		Action: "stop",
		Entity: "database",
		API:    "rds",
		Params: new(StopDatabase).ParamsSpec().Rule(),
	},
	"stopinstance": Definition{
		Action: "stop",
		Entity: "instance",
		API:    "ec2",
		Params: new(StopInstance).ParamsSpec().Rule(),
	},
	"stoptrail": Definition{
		Action: "stop",
		Entity: "trail",
		API:    "cloudtrail",
		Params: new(StopTrail).ParamsSpec().Rule(),
	},
	"updatebucket": Definition{
		Action: "update",
		Entity: "bucket",
		API:    "s3",
		Params: new(UpdateBucket).ParamsSpec().Rule(),
	},
	"updateclassicloadbalancer": Definition{
		Action: "update",
		Entity: "classicloadbalancer",
		API:    "elb",
		Params: new(UpdateClassicLoadbalancer).ParamsSpec().Rule(),
	},
	"updatecontainertask": Definition{
		Action: "update",
		Entity: "containertask",
		API:    "ecs",
		Params: new(UpdateContainertask).ParamsSpec().Rule(),
	},
	"updatedistribution": Definition{
		Action: "update",
		Entity: "distribution",
		API:    "cloudfront",
		Params: new(UpdateDistribution).ParamsSpec().Rule(),
	},
	"updateimage": Definition{
		Action: "update",
		Entity: "image",
		API:    "ec2",
		Params: new(UpdateImage).ParamsSpec().Rule(),
	},
	"updateinstance": Definition{
		Action: "update",
		Entity: "instance",
		API:    "ec2",
		Params: new(UpdateInstance).ParamsSpec().Rule(),
	},
	"updateloggroup": Definition{
		Action: "update",
		Entity: "loggroup",
		API:    "cloudwatchlogs",
		Params: new(UpdateLoggroup).ParamsSpec().Rule(),
	},
	"updateloginprofile": Definition{
		Action: "update",
		Entity: "loginprofile",
		API:    "iam",
		Params: new(UpdateLoginprofile).ParamsSpec().Rule(),
	},
	"updatepolicy": Definition{
		Action: "update",
		Entity: "policy",
		API:    "iam",
		Params: new(UpdatePolicy).ParamsSpec().Rule(),
	},
	"updaterecord": Definition{
		Action: "update",
		Entity: "record",
		API:    "route53",
		Params: new(UpdateRecord).ParamsSpec().Rule(),
	},
	"updates3object": Definition{
		Action: "update",
		Entity: "s3object",
		API:    "s3",
		Params: new(UpdateS3object).ParamsSpec().Rule(),
	},
	"updatescalinggroup": Definition{
		Action: "update",
		Entity: "scalinggroup",
		API:    "autoscaling",
		Params: new(UpdateScalinggroup).ParamsSpec().Rule(),
	},
	"updatesecret": Definition{
		Action: "update",
		Entity: "secret",
		API:    "secretsmanager",
		Params: new(UpdateSecret).ParamsSpec().Rule(),
	},
	"updatesecuritygroup": Definition{
		Action: "update",
		Entity: "securitygroup",
		API:    "ec2",
		Params: new(UpdateSecuritygroup).ParamsSpec().Rule(),
	},
	"updatessmparameter": Definition{
		Action: "update",
		Entity: "ssmparameter",
		API:    "ssm",
		Params: new(UpdateSsmparameter).ParamsSpec().Rule(),
	},
	"updatestack": Definition{
		Action: "update",
		Entity: "stack",
		API:    "cloudformation",
		Params: new(UpdateStack).ParamsSpec().Rule(),
	},
	"updatesubnet": Definition{
		Action: "update",
		Entity: "subnet",
		API:    "ec2",
		Params: new(UpdateSubnet).ParamsSpec().Rule(),
	},
	"updatetargetgroup": Definition{
		Action: "update",
		Entity: "targetgroup",
		API:    "elbv2",
		Params: new(UpdateTargetgroup).ParamsSpec().Rule(),
	},
}

var DriverSupportedActions = map[string][]string{
	"attach":       []string{"alarm", "classicloadbalancer", "containertask", "elasticip", "instance", "instanceprofile", "internetgateway", "listener", "mfadevice", "networkinterface", "policy", "role", "routetable", "securitygroup", "user", "volume"},
	"authenticate": []string{"registry"},
	"check":        []string{"certificate", "database", "distribution", "instance", "loadbalancer", "natgateway", "networkinterface", "scalinggroup", "securitygroup", "volume"},
	"copy":         []string{"image", "snapshot"},
	"create":       []string{"accesskey", "alarm", "apigateway", "apigatewayroute", "apigatewaystage", "appscalingpolicy", "appscalingtarget", "bucket", "certificate", "classicloadbalancer", "containercluster", "database", "dbsubnetgroup", "distribution", "dynamodbtable", "ekscluster", "eksnodegroup", "elasticip", "filesystem", "function", "group", "image", "instance", "instanceprofile", "internetgateway", "keypair", "launchconfiguration", "listener", "loadbalancer", "loggroup", "loginprofile", "mfadevice", "natgateway", "networkinterface", "policy", "queue", "record", "repository", "role", "route", "routetable", "s3object", "scalinggroup", "scalingpolicy", "secret", "securitygroup", "snapshot", "ssmparameter", "stack", "subnet", "subscription", "tag", "targetgroup", "topic", "trail", "user", "volume", "vpc", "zone"},
	"delete":       []string{"accesskey", "alarm", "apigateway", "apigatewayroute", "apigatewaystage", "appscalingpolicy", "appscalingtarget", "bucket", "certificate", "classicloadbalancer", "containercluster", "containertask", "database", "dbsubnetgroup", "distribution", "dynamodbtable", "ekscluster", "eksnodegroup", "elasticip", "filesystem", "function", "group", "image", "instance", "instanceprofile", "internetgateway", "keypair", "launchconfiguration", "listener", "loadbalancer", "loggroup", "loginprofile", "mfadevice", "natgateway", "networkinterface", "policy", "queue", "record", "repository", "role", "route", "routetable", "s3object", "scalinggroup", "scalingpolicy", "secret", "securitygroup", "snapshot", "ssmparameter", "stack", "subnet", "subscription", "tag", "targetgroup", "topic", "trail", "user", "volume", "vpc", "zone"},
	"detach":       []string{"alarm", "classicloadbalancer", "containertask", "elasticip", "instance", "instanceprofile", "internetgateway", "mfadevice", "networkinterface", "policy", "role", "routetable", "securitygroup", "user", "volume"},
	"import":       []string{"image"},
	"restart":      []string{"database", "instance"},
	"start":        []string{"alarm", "containertask", "database", "instance", "trail"},
	"stop":         []string{"alarm", "containertask", "database", "instance", "trail"},
	"update":       []string{"bucket", "classicloadbalancer", "containertask", "distribution", "image", "instance", "loggroup", "loginprofile", "policy", "record", "s3object", "scalinggroup", "secret", "securitygroup", "ssmparameter", "stack", "subnet", "targetgroup"},
}
