/* Copyright 2017 WALLIX

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// DO NOT EDIT
// This file was automatically generated with go generate
package ast

// entities is the set the template parser accepts. Derived from the `entity:`
// struct tags in aws/spec, plus a small set of entities kept parseable so that
// template history already written to ~/.awless still loads. See
// gen/aws/generators/entities.go.
var entities = map[Entity]struct{}{
	"accesskey":                {},
	"alarm":                    {},
	"apigateway":               {},
	"apigatewayroute":          {},
	"apigatewaystage":          {},
	"application":              {},
	"appscalingpolicy":         {},
	"appscalingtarget":         {},
	"broker":                   {},
	"bucket":                   {},
	"buildproject":             {},
	"cachecluster":             {},
	"cachesubnetgroup":         {},
	"certificate":              {},
	"classicloadbalancer":      {},
	"configrule":               {},
	"configurationset":         {},
	"container":                {},
	"containercluster":         {},
	"containerservice":         {},
	"containertask":            {},
	"crawler":                  {},
	"database":                 {},
	"dbsubnetgroup":            {},
	"deployapplication":        {},
	"deployment":               {},
	"deploymentgroup":          {},
	"distribution":             {},
	"dynamodbtable":            {},
	"ekscluster":               {},
	"eksnodegroup":             {},
	"elasticip":                {},
	"emailidentity":            {},
	"environment":              {},
	"eventbus":                 {},
	"eventrule":                {},
	"eventtarget":              {},
	"execution":                {},
	"filesystem":               {},
	"fsxbackup":                {},
	"fsxfilesystem":            {},
	"function":                 {},
	"gluedatabase":             {},
	"group":                    {},
	"identitypool":             {},
	"image":                    {},
	"instance":                 {},
	"instanceprofile":          {},
	"internetgateway":          {},
	"ipset":                    {},
	"job":                      {},
	"kafkacluster":             {},
	"keypair":                  {},
	"launchconfiguration":      {},
	"listener":                 {},
	"loadbalancer":             {},
	"loggroup":                 {},
	"loginprofile":             {},
	"mfadevice":                {},
	"natgateway":               {},
	"networkinterface":         {},
	"none":                     {},
	"pipeline":                 {},
	"policy":                   {},
	"queue":                    {},
	"record":                   {},
	"redshiftcluster":          {},
	"redshiftsubnetgroup":      {},
	"registry":                 {},
	"replicationgroup":         {},
	"repository":               {},
	"role":                     {},
	"route":                    {},
	"routetable":               {},
	"rulegroup":                {},
	"s3object":                 {},
	"scalinggroup":             {},
	"scalingpolicy":            {},
	"secret":                   {},
	"securitygroup":            {},
	"snapshot":                 {},
	"ssmparameter":             {},
	"stack":                    {},
	"statemachine":             {},
	"stream":                   {},
	"subnet":                   {},
	"subscription":             {},
	"tag":                      {},
	"targetgroup":              {},
	"topic":                    {},
	"trail":                    {},
	"transitgateway":           {},
	"transitgatewayattachment": {},
	"transitgatewayroutetable": {},
	"user":                     {},
	"userpool":                 {},
	"volume":                   {},
	"vpc":                      {},
	"vpcendpoint":              {},
	"webacl":                   {},
	"zone":                     {},
}
