package awsdoc

import "strings"

func TemplateParamsDoc(action, entity, param string) (string, bool) {
	doc, ok := paramsDoc[action+"."+entity][param]
	return doc, ok
}

func TemplateParamsDocWithEnums(action, entity, param string) (string, bool) {
	var suffix string
	if enum, ok := EnumDoc[action+"."+entity+"."+param]; ok && len(enum) > 0 && strings.TrimSpace(enum[0]) != "" {
		suffix = " (" + strings.Join(enum, " | ") + ")"
	}
	doc, ok := TemplateParamsDoc(action, entity, param)
	return doc + suffix, ok
}

var paramsDoc = map[string]map[string]string{
	"attach.alarm": {
		"action-arn": "The Amazon Resource Name (ARN) of the action to execute when this alarm transitions to the ALARM state from any other state",
		"name":       "The Name of the Alarm to update",
	},
	"attach.classicloadbalancer": {
		"instance": "The ID of the instance",
		"name":     "The name of the Classic load balancer",
	},
	"attach.containertask": {
		"command":           "The command that is passed to the container",
		"container-name":    "The name of a container",
		"env":               "The environment variables to pass to a container using this format: [key1:val1,key2:val2,...]",
		"image":             "The image used to start a container. Images in the Docker Hub registry are available by default. Other repositories are specified with repository-url/image:tag",
		"memory-hard-limit": "The hard limit (in MiB) of memory to present to the container. If your container attempts to exceed the memory specified here, the container is killed",
		"name":              "The name of the new or existing task containing the container to attach",
		"ports":             "The list of port mappings for the container. Port mappings allow containers to access ports on the host container instance to send or receive traffic (format [host-port:]container-port[/protocol][,[host-port:]container-port[/protocol]])",
		"privileged":        "When this parameter is true, the container is given elevated privileges on the host container instance",
		"workdir":           "The working directory in which to run commands inside the container",
	},
	"attach.elasticip": {
		"allow-reassociation": "Specify false to ensure the operation fails if the Elastic IP address is already associated with another resource",
		"id":                  "The allocation ID",
		"instance":            "The ID of the instance",
		"networkinterface":    "The ID of the network interface",
		"privateip":           "The primary or secondary private IP address to associate with the Elastic IP address",
	},
	"attach.instance": {
		"id":          "The ID of the Instance",
		"port":        "The port on which the Instance is listenning",
		"targetgroup": "The Amazon Resource Name (ARN) of the target group",
	},
	"attach.instanceprofile": {
		"instance": "The ID of the Instance",
		"name":     "The name of the InstanceProfile to associate to the Instance",
		"replace":  "If 'true' will replace existing instance profile with provided one",
	},
	"attach.internetgateway": {
		"id":  "The ID of the Internet gateway",
		"vpc": "The ID of the VPC",
	},
	"attach.listener": {
		"certificate": "The awless alias of the certificate's name (ex: @www.mysite.com), or the full certificate's ARN",
		"id":          "The Amazon Resource Name (ARN) of the listener",
	},
	"attach.mfadevice": {
		"id":         "The serial number that uniquely identifies the MFA device",
		"mfa-code-1": "An authentication code emitted by the device",
		"mfa-code-2": "A subsequent authentication code emitted by the device",
		"no-prompt":  "Use 'true' to disable the prompt that asks to append the mfadevice to ~/.aws/config file",
		"user":       "The name of the IAM user for whom you want to enable the MFA device",
	},
	"attach.networkinterface": {
		"device-index": "The index of the device for the network interface attachment",
		"id":           "The ID of the network interface",
		"instance":     "The ID of the instance",
	},
	"attach.policy": {
		"access":  "Type of access to retrieve an AWS policy",
		"arn":     "The Amazon Resource Name (ARN) of the IAM policy you want to attach",
		"group":   "The name (friendly name, not ARN) of the IAM group to attach the policy to",
		"role":    "The name (friendly name, not ARN) of the IAM role to attach the policy to",
		"service": "Service string to retrieve an AWS policy",
		"user":    "The name (friendly name, not ARN) of the IAM user to attach the policy to",
	},
	"attach.role": {
		"instanceprofile": "The name of the instance profile to update",
		"name":            "The name of the role to add",
	},
	"attach.routetable": {
		"id":     "The ID of the route table",
		"subnet": "The ID of the subnet",
	},
	"attach.securitygroup": {
		"id":       "The ID of the Security Group to add to the instance",
		"instance": "The ID of the Instance",
	},
	"attach.user": {
		"group": "The name of the group to update",
		"name":  "The name of the user to add",
	},
	"attach.volume": {
		"device":   "The device name (for example, /dev/sdh or xvdh)",
		"id":       "The ID of the EBS volume",
		"instance": "The ID of the instance",
	},
	"authenticate.registry": {
		"accounts":        "A list of AWS account IDs that are associated with the registries for which to authenticate",
		"no-confirm":      "Do not ask confirmation before effectively running `docker login` command",
		"no-docker-login": "Set to 'true' to disable the prompt and automatic execution of `docker login` command",
	},
	"check.certificate": {
		"arn":     "The Amazon Resource Name (ARN) of the certificate to check",
		"state":   "The state of the certificate to reach",
		"timeout": "The time (in seconds) after which the check is failed",
	},
	"check.database": {
		"id":      "The ID of the RDS Database to check",
		"state":   "The state of the RDS Database to reach",
		"timeout": "The time (in seconds) after which the check is failed",
	},
	"check.distribution": {
		"id":      "The ID of the CloudFront Distribution to check",
		"state":   "The state of the CloudFront Distribution to reach",
		"timeout": "The time (in seconds) after which the check is failed",
	},
	"check.instance": {
		"id":      "The ID of the EC2 Instance to check",
		"state":   "The state of the EC2 Instance to reach",
		"timeout": "The time (in seconds) after which the check is failed",
	},
	"check.loadbalancer": {
		"id":      "The ID of the ELBv2 Loadbalancer to check",
		"state":   "The state of the ELBv2 Loadbalancer to reach",
		"timeout": "The time (in seconds) after which the check is failed",
	},
	"check.natgateway": {
		"id":      "The ID of the NAT Gateway to check",
		"state":   "The state of the NAT Gateway to reach",
		"timeout": "The time (in seconds) after which the check is failed",
	},
	"check.networkinterface": {
		"id":      "The ID of the Network Interface to check",
		"state":   "The state of the Network Interface to reach",
		"timeout": "The time (in seconds) after which the check is failed",
	},
	"check.scalinggroup": {
		"count":   "The number of Instances + Loadbalancers + TargetGroups in the AutoScaling Group to reach",
		"name":    "The name of the AutoScaling Group to check",
		"timeout": "The time (in seconds) after which the check is failed",
	},
	"check.securitygroup": {
		"id":      "The ID of the EC2 Security Group to check",
		"state":   "The state of the EC2 Security Group to reach",
		"timeout": "The time (in seconds) after which the check is failed",
	},
	"check.volume": {
		"id":      "The ID of the EC2 Volume to check",
		"state":   "The state of the EC2 Volume to reach",
		"timeout": "The time (in seconds) after which the check is failed",
	},
	"copy.image": {
		"description":   "A description for the new AMI in the destination region",
		"encrypted":     "Specifies whether the destination snapshots of the copied image should be encrypted",
		"name":          "The name of the new AMI in the destination region",
		"source-id":     "The ID of the AMI to copy",
		"source-region": "The name of the region that contains the AMI to copy",
	},
	"copy.snapshot": {
		"description":   "A description for the EBS snapshot",
		"encrypted":     "Specifies whether the destination snapshot should be encrypted",
		"source-id":     "The ID of the EBS snapshot to copy",
		"source-region": "The ID of the region that contains the snapshot to be copied",
	},
	"create.accesskey": {
		"no-prompt": "Deprecated - use the save param",
		"save":      "Use 'true' to save the access key in ~/.aws/credentials under 'user' profile; use 'false' to disable the prompt",
		"user":      "The name of the user for which the access key will be generated",
	},
	"create.alarm": {
		"alarm-actions":            "The actions to execute when this alarm transitions to the ALARM state from any other state",
		"description":              "The description for the alarm",
		"dimensions":               "The dimensions for the metric associated with the alarm",
		"enabled":                  "Indicates whether actions should be executed during any changes to the alarm state",
		"evaluation-periods":       "The number of periods over which data is compared to the specified threshold",
		"insufficientdata-actions": "The actions to execute when this alarm transitions to the INSUFFICIENT_DATA state from any other state",
		"metric":                   "The name for the metric associated with the alarm",
		"name":                     "The name for the alarm",
		"namespace":                "The namespace for the metric associated with the alarm",
		"ok-actions":               "The actions to execute when this alarm transitions to an OK state from any other state",
		"operator":                 "The arithmetic operation to use when comparing the specified statistic and threshold",
		"period":                   "The period, in seconds, over which the specified statistic is applied",
		"statistic-function":       "The statistic for the metric associated with the alarm, other than percentile",
		"threshold":                "The value against which the specified statistic is compared",
		"unit":                     "The unit of measure for the statistic",
	},
	"create.appscalingpolicy": {
		"dimension":                            "The scalable dimension associated with the scalable target",
		"name":                                 "The name of the scaling policy",
		"resource":                             "The identifier of the resource associated with the scalable target (eg. for ECS: service/cluster-name/service-deployment-name, for EC2 spot-fleet: spot-fleet-request/sfr-73fbd2ce-aa30-494c-8788-1cee4EXAMPLE, for EMR cluster: instancegroup/j-2EEZNYKUA1NTV/ig-1791Y4E1L8YI0, for AppStream 2.0 fleet: fleet/sample-fleet, for DynamoDB table: table/my-table, for DynamoDB global secondary index: table/my-table/index/my-table-index)",
		"service-namespace":                    "The namespace of the AWS service",
		"stepscaling-adjustment-type":          "The scalable dimension",
		"stepscaling-adjustments":              "A set of adjustments that enable you to scale based on the size of the alarm breach using this format: [[from]:[to]:scaling-adjustment[,[from]:[to]:scaling-adjustment[,...]]]",
		"stepscaling-aggregation-type":         "The aggregation type for the CloudWatch metrics",
		"stepscaling-cooldown":                 "The amount of time, in seconds, after a scaling activity completes where previous trigger-related scaling activities can influence future scaling events",
		"stepscaling-min-adjustment-magnitude": "The minimum number to adjust your scalable dimension as a result of a scaling activity",
		"type":                                 "The policy type",
	},
	"create.appscalingtarget": {
		"dimension":         "The scalable dimension associated with the scalable target",
		"max-capacity":      "The maximum value to scale to in response to a scale out event",
		"min-capacity":      "The minimum value to scale to in response to a scale in event",
		"resource":          "The identifier of the resource associated with the scalable target (eg. for ECS: service/cluster-name/service-deployment-name, for EC2 spot-fleet: spot-fleet-request/sfr-73fbd2ce-aa30-494c-8788-1cee4EXAMPLE, for EMR cluster: instancegroup/j-2EEZNYKUA1NTV/ig-1791Y4E1L8YI0, for AppStream 2.0 fleet: fleet/sample-fleet, for DynamoDB table: table/my-table, for DynamoDB global secondary index: table/my-table/index/my-table-index)",
		"role":              "The ARN of an IAM role that allows Application Auto Scaling to modify the scalable target on your behalf",
		"service-namespace": "The namespace of the AWS service",
	},
	"create.secret": {
		"name":        "Name of the secret",
		"secret":      "Secret value to store",
		"description": "Description of the secret",
		"kms-key":     "ARN or ID of the KMS key used to encrypt the secret (defaults to the account's aws/secretsmanager key)",
	},
	"update.secret": {
		"id":          "Name or ARN of the secret to update",
		"secret":      "New secret value",
		"description": "New description of the secret",
		"kms-key":     "ARN or ID of the KMS key used to encrypt the secret",
	},
	"delete.secret": {
		"id":              "Name or ARN of the secret to delete",
		"recovery-window": "Days before permanent deletion, between 7 and 30 (defaults to 30); cannot be combined with force",
		"force":           "Delete immediately with no recovery window; cannot be undone",
	},
	"create.ssmparameter": {
		"name":        "Name of the parameter, optionally a path such as /app/db/host",
		"value":       "Value of the parameter",
		"type":        "Type of the parameter",
		"description": "Description of the parameter",
		"kms-key":     "ARN or ID of the KMS key used to encrypt a SecureString parameter",
		"tier":        "Parameter tier",
	},
	"update.ssmparameter": {
		"name":        "Name of the parameter to update",
		"value":       "New value of the parameter",
		"type":        "Type of the parameter",
		"description": "Description of the parameter",
		"kms-key":     "ARN or ID of the KMS key used to encrypt a SecureString parameter",
		"overwrite":   "Overwrite an existing parameter (defaults to true for update)",
	},
	"delete.ssmparameter": {
		"name": "Name of the parameter to delete",
	},
	"create.dynamodbtable": {
		"name":           "Name of the table",
		"partition-key":  "Name of the partition (hash) key attribute",
		"partition-type": "Type of the partition key attribute",
		"sort-key":       "Name of the sort (range) key attribute",
		"sort-type":      "Type of the sort key attribute",
		"billing-mode":   "Billing mode; defaults to PAY_PER_REQUEST unless a capacity is given",
		"read-capacity":  "Provisioned read capacity units; requires billing-mode=PROVISIONED",
		"write-capacity": "Provisioned write capacity units; requires billing-mode=PROVISIONED",
	},
	"delete.dynamodbtable": {
		"name": "Name of the table to delete",
	},
	"create.ekscluster": {
		"name":                "Name of the cluster",
		"role":                "ARN of the IAM role the EKS control plane assumes",
		"subnets":             "Subnet ids for the control plane; at least two in different availability zones",
		"securitygroups":      "Security group ids for the control plane",
		"version":             "Kubernetes version, for example 1.29 (defaults to the latest supported)",
		"public-access":       "Enable public access to the API server endpoint",
		"private-access":      "Enable private access to the API server endpoint",
		"public-access-cidrs": "CIDR blocks allowed to reach the public API server endpoint",
	},
	"delete.ekscluster": {
		"name": "Name of the cluster to delete",
	},
	"create.eksnodegroup": {
		"name":          "Name of the node group",
		"cluster":       "Name of the cluster to add the node group to",
		"role":          "ARN of the IAM role the nodes assume",
		"subnets":       "Subnet ids the nodes launch into",
		"instance-type": "EC2 instance type for the nodes",
		"min-size":      "Minimum number of nodes",
		"max-size":      "Maximum number of nodes",
		"desired-size":  "Desired number of nodes (defaults to 2)",
		"disk-size":     "Root volume size in GiB",
		"ami-type":      "AMI type for the nodes",
	},
	"delete.eksnodegroup": {
		"name":    "Name of the node group to delete",
		"cluster": "Name of the cluster the node group belongs to",
	},
	"create.filesystem": {
		"token":            "Creation token, used by the API as an idempotency key",
		"performance-mode": "Performance mode of the file system",
		"throughput-mode":  "Throughput mode of the file system",
		"encrypted":        "Encrypt the file system at rest",
		"kms-key":          "ARN or ID of the KMS key used for encryption",
	},
	"delete.filesystem": {
		"id": "Id of the file system to delete",
	},
	"create.trail": {
		"name":           "Name of the trail",
		"bucket":         "Name of the S3 bucket the trail delivers logs to",
		"prefix":         "Key prefix for delivered log files",
		"multiregion":    "Apply the trail to all regions",
		"global-events":  "Include events from global services such as IAM",
		"log-validation": "Enable log file integrity validation",
		"kms-key":        "ARN or ID of the KMS key used to encrypt log files",
		"sns-topic":      "Name of the SNS topic notified on log delivery",
		"organization":   "Apply the trail to the whole AWS organization",
	},
	"delete.trail": {"name": "Name or ARN of the trail to delete"},
	"start.trail":  {"name": "Name or ARN of the trail to start logging"},
	"stop.trail":   {"name": "Name or ARN of the trail to stop logging"},
	"create.loggroup": {
		"name":    "Name of the log group",
		"kms-key": "ARN of the KMS key used to encrypt the log data",
	},
	"delete.loggroup": {"name": "Name of the log group to delete"},
	"update.loggroup": {
		"name":      "Name of the log group",
		"retention": "Days to retain log events; CloudWatch Logs accepts only a fixed set of values",
	},
	"create.cachecluster": {
		"id":                 "Identifier for the cache cluster",
		"engine":             "Cache engine to run: redis, valkey or memcached",
		"engine-version":     "Version of the cache engine",
		"type":               "Node type, e.g. cache.t3.micro",
		"nodes":              "Number of cache nodes in the cluster; memcached supports more than one",
		"subnet-group":       "Name of the cache subnet group placing the cluster in a VPC",
		"securitygroups":     "Identifiers of the VPC security groups for the cluster",
		"port":               "Port the cache engine listens on",
		"zone":               "Availability zone to create the cluster in",
		"replication-group":  "Identifier of the replication group to join as a read replica",
		"parameter-group":    "Name of the cache parameter group to apply",
		"snapshot-retention": "Days to retain automatic snapshots; zero disables them",
	},
	"delete.cachecluster": {
		"id":       "Identifier of the cache cluster to delete",
		"snapshot": "Name of a final snapshot to take before deleting",
	},
	"update.cachecluster": {
		"id":                 "Identifier of the cache cluster to modify",
		"nodes":              "New number of cache nodes",
		"type":               "New node type",
		"engine-version":     "Cache engine version to upgrade to",
		"securitygroups":     "Identifiers of the VPC security groups to apply",
		"maintenance-window": "Weekly window for maintenance, e.g. sun:23:00-mon:01:30",
		"apply-immediately":  "Apply the change now rather than in the next maintenance window",
	},
	"create.cachesubnetgroup": {
		"name":        "Name for the cache subnet group",
		"description": "Description of the cache subnet group",
		"subnets":     "Identifiers of the subnets to include",
	},
	"delete.cachesubnetgroup": {"name": "Name of the cache subnet group to delete"},
	"update.cachesubnetgroup": {
		"name":        "Name of the cache subnet group to modify",
		"description": "New description of the cache subnet group",
		"subnets":     "New set of subnet identifiers, replacing the current one",
	},
	"create.replicationgroup": {
		"id":                 "Identifier for the replication group",
		"description":        "Description of the replication group",
		"engine":             "Cache engine to run: redis or valkey",
		"engine-version":     "Version of the cache engine",
		"type":               "Node type, e.g. cache.t3.micro",
		"clusters":           "Number of nodes in the group, counting the primary and its replicas",
		"subnet-group":       "Name of the cache subnet group placing the group in a VPC",
		"securitygroups":     "Identifiers of the VPC security groups for the group",
		"port":               "Port the cache engine listens on",
		"multi-az":           "Spread the primary and replicas across availability zones",
		"automatic-failover": "Promote a replica automatically if the primary fails",
		"at-rest-encryption": "Encrypt the data stored on disk",
		"transit-encryption": "Encrypt the connections between clients and the group",
		"snapshot-retention": "Days to retain automatic snapshots; zero disables them",
	},
	"delete.replicationgroup": {
		"id":             "Identifier of the replication group to delete",
		"snapshot":       "Name of a final snapshot to take before deleting",
		"retain-primary": "Delete only the replicas, leaving the primary node running",
	},
	"create.eventbus": {
		"name":        "Name for the event bus",
		"description": "Description of the event bus",
		"source":      "Name of the partner event source to back the bus with",
		"kms-key":     "Identifier of the KMS key used to encrypt events at rest",
	},
	"delete.eventbus": {"name": "Name of the event bus to delete"},
	"create.eventrule": {
		"name":        "Name for the rule",
		"description": "Description of the rule",
		"eventbus":    "Name of the event bus to put the rule on; defaults to the account default bus",
		"pattern":     "JSON event pattern the rule matches on",
		"schedule":    "Schedule for the rule, e.g. rate(5 minutes) or cron(0 12 * * ? *)",
		"role":        "ARN of the IAM role the rule assumes",
		"state":       "Whether the rule is ENABLED or DISABLED",
	},
	"update.eventrule": {
		"name":        "Name of the rule to update",
		"description": "New description of the rule",
		"eventbus":    "Name of the event bus the rule is on",
		"pattern":     "JSON event pattern the rule matches on",
		"schedule":    "Schedule for the rule, e.g. rate(5 minutes) or cron(0 12 * * ? *)",
		"role":        "ARN of the IAM role the rule assumes",
		"state":       "Whether the rule is ENABLED or DISABLED",
	},
	"delete.eventrule": {
		"name":     "Name of the rule to delete",
		"eventbus": "Name of the event bus the rule is on",
		"force":    "Delete the rule even though it still has targets attached",
	},
	"start.eventrule": {
		"name":     "Name of the rule to enable",
		"eventbus": "Name of the event bus the rule is on",
	},
	"stop.eventrule": {
		"name":     "Name of the rule to disable",
		"eventbus": "Name of the event bus the rule is on",
	},
	"attach.eventtarget": {
		"rule":     "Name of the rule to attach the target to",
		"id":       "Identifier for the target within the rule",
		"arn":      "ARN of the resource the rule invokes",
		"role":     "ARN of the IAM role used to invoke the target",
		"input":    "Constant JSON passed to the target instead of the matched event",
		"eventbus": "Name of the event bus the rule is on",
	},
	"detach.eventtarget": {
		"rule":     "Name of the rule to detach the target from",
		"id":       "Identifiers of the targets to remove",
		"eventbus": "Name of the event bus the rule is on",
		"force":    "Remove the target even if the rule is managed by another service",
	},
	"create.apigateway": {
		"name":        "Name of the API",
		"protocol":    "Protocol of the API",
		"description": "Description of the API",
		"target":      "Target of a quick-create integration, such as a Lambda function ARN",
		"version":     "Version identifier of the API",
		"route-key":   "Route key for a quick-create route, such as \"GET /items\"",
	},
	"delete.apigateway": {"id": "Id of the API to delete"},
	"create.apigatewayroute": {
		"api":        "Id of the API the route belongs to",
		"route-key":  "Route key, such as \"GET /items\" or $default",
		"target":     "Integration target, in the form integrations/<integration-id>",
		"authorizer": "Id of the authorizer for the route",
		"auth-type":  "Authorization type for the route",
	},
	"delete.apigatewayroute": {
		"api": "Id of the API the route belongs to",
		"id":  "Id of the route to delete",
	},
	"create.apigatewaystage": {
		"api":         "Id of the API the stage belongs to",
		"name":        "Name of the stage",
		"autodeploy":  "Automatically deploy changes to this stage",
		"deployment":  "Id of the deployment to associate with the stage",
		"description": "Description of the stage",
	},
	"delete.apigatewaystage": {
		"api":  "Id of the API the stage belongs to",
		"name": "Name of the stage to delete",
	},
	"create.bucket": {
		"acl":  "The canned ACL to apply to the bucket",
		"name": "The name of bucket to create",
	},
	"create.certificate": {
		"domains":            "Main and Additional Fully qualified domain names (FQDNs) to be included in the Certificate name and Subject Alternative Name of the ACM Certificate",
		"validation-domains": "The domain name that you want ACM to use to send you validation emails. This domain name is the suffix of the email addresses that you want ACM to use. This must be the same as the DomainName value or a superdomain of the domain value",
	},
	"create.classicloadbalancer": {
		"healthcheck-path": "The healthcheck ping path only. Otherwise default to ping port 80 using TCP. Ex: home.html (protocol and port are derived from the first listener)",
		"listeners":        "The list of listeners. Format for a listener: LOADB_PROTO:LOADB_PORT:INST_PROTO:INST_PORT . Ex: [HTTPS:443:HTTP:8080,TCP:53:TCP:4567]",
		"name":             "The name of the Classic load balancer",
		"scheme":           "The nodes of an Internet-facing load balancer have public IP addresses",
		"securitygroups":   "[Application Load Balancers] The IDs of the security groups to assign to the load balancer",
		"subnets":          "The IDs of the subnets to attach to the load balancer",
		"tags":             "A list of tags to assign to the load balancer. Example: tags=Env:Prod,Country:US",
		"zones":            "At least 1 availability zone from the same region as the load balancer",
	},
	"create.containercluster": {
		"name": "The name of your cluster",
	},
	"create.database": {
		"autoupgrade":        "Set to true to indicate that minor version patches are applied automatically",
		"availabilityzone":   "Specifies the name of the Availability Zone the DB instance is located in",
		"backupretention":    "Specifies the number of days for which automatic DB snapshots are retained",
		"backupwindow":       "Specifies the daily time range during which automated backups are created if automated backups are enabled, as determined by the BackupRetentionPeriod (format hh24:mi-hh24:mi)",
		"cluster":            "If the DB instance is a member of a DB cluster, contains the name of the DB cluster that the DB instance is a member of",
		"copytagstosnapshot": "True to copy all tags from the READ replica to snapshots of the READ Replica. Default is false",
		"dbname":             "The name of the database to create when the DB instance is created",
		"dbsecuritygroups":   "A list of DB security groups to associate with this DB instance",
		"domain":             "Specify the Active Directory Domain to create the instance in",
		"encrypted":          "Specifies whether the DB instance is encrypted",
		"engine":             "The name of the database engine to be used for this DB instance (not every engine is available for every region)",
		"iamrole":            "Specify the name of the IAM role to be used when making API calls to the Directory Service",
		"id":                 "Contains a user-supplied database identifier",
		"iops":               "Specifies the Provisioned IOPS (I/O operations per second) value",
		"license":            "License model information for this DB instance",
		"maintenancewindow":  "Specifies the weekly time range during which system maintenance can occur, in Universal Coordinated Time (UTC)",
		"multiaz":            "Specifies if the DB instance is a Multi-AZ deployment",
		"optiongroup":        "Indicates that the DB instance should be associated with the specified option group",
		"parametergroup":     "The name of the DB parameter group to associate with this DB instance",
		"password":           "The password for the master database user",
		"port":               "The port number on which the database accepts connections",
		"public":             "'true' specifies an Internet-facing instance with a publicly resolvable DNS name, which resolves to a public IP address. 'false' specifies an internal instance with a DNS name that resolves to a private IP address",
		"replica":            "The DB instance identifier of the READ replica",
		"replica-source":     "The identifier of the DB instance that will act as the source for the READ replica (each DB instance can have up to 5 Read replicas). Use the Amazon Resource Name (ARN) of the database if it is not in the same region",
		"size":               "Specifies the allocated storage size specified in gigabytes",
		"storagetype":        "Specifies the storage type associated with DB instance",
		"subnetgroup":        "A DB subnet group to associate with this DB instance",
		"timezone":           "The time zone of the DB instance",
		"type":               "Contains the name of the compute and memory capacity class of the DB instance",
		"username":           "Contains the master username for the DB instance",
		"version":            "Indicates the database engine version",
		"vpcsecuritygroups":  "A list of EC2 VPC security groups to associate with this DB instance",
	},
	"create.dbsubnetgroup": {
		"description": "The description for the DB subnet group",
		"name":        "The name for the DB subnet group",
		"subnets":     "The EC2 Subnet IDs for the DB subnet group",
	},
	"create.distribution": {
		"certificate":     "The Amazon Resource Name (ARN) of the AWS Certificate Manager (ACM) certificate you want to use for TSL connection",
		"comment":         "Any comments you want to include about the distribution",
		"default-file":    "The object that you want CloudFront to request from your origin when a viewer requests the root URL for your distribution (http://www.example.com)",
		"domain-aliases":  "A list of CNAMEs (alternate domain names), if any, for this distribution",
		"enable":          "From this field, you can enable or disable the selected distribution",
		"forward-cookies": "Specifies which cookies to forward to the origin for this cache behavior",
		"forward-queries": "Indicates whether you want CloudFront to forward query strings to the origin that is associated with this cache behavior and cache based on the query string parameters",
		"https-behavior":  "The protocol (HTTP or HTTPS) that viewers can use to access the files",
		"min-ttl":         "The minimum amount of time that you want objects to stay in CloudFront caches before CloudFront forwards another request to your origin to determine whether the object has been updated",
		"origin-domain":   "The DNS name of the Amazon S3 bucket from which you want CloudFront to get objects for this origin, for example, myawsbucket.s3.amazonaws.com",
		"origin-path":     "An optional element that causes CloudFront to request your content from a directory in your Amazon S3 bucket or your custom origin. When you include this element, specify the directory name, beginning with a /",
		"price-class":     "The price class that corresponds with the maximum price that you want to pay for CloudFront service. If you specify PriceClass_All, CloudFront responds to requests for your objects from all CloudFront edge locations",
	},
	"create.elasticip": {
		"domain": "Set to vpc to allocate the address for use with instances in a VPC else the address is for use with instances in EC2-Classic",
	},
	"create.function": {
		"bucket":        "Amazon S3 bucket name where the .zip file containing your deployment package is stored. This bucket must reside in the same AWS region where you are creating the Lambda function",
		"description":   "A short, user-defined function description",
		"handler":       "The function within your code that Lambda calls to begin execution",
		"memory":        "The amount of memory, in MB, your Lambda function is given",
		"name":          "The name you want to assign to the function you are uploading",
		"object":        "The Amazon S3 object (the deployment package) key name you want to upload",
		"objectversion": "The Amazon S3 object (the deployment package) version you want to upload",
		"publish":       "This boolean parameter can be used to request AWS Lambda to create the Lambda function and publish a version as an atomic operation",
		"role":          "The Amazon Resource Name (ARN) of the IAM role that Lambda assumes when it executes your function to access any other Amazon Web Services (AWS) resources",
		"runtime":       "The runtime environment for the Lambda function you are uploading",
		"timeout":       "The function execution time at which Lambda should terminate the function",
		"zipfile":       "The path toward the zip file containing your deployment package",
	},
	"create.group": {
		"name": "The name of the group to create",
	},
	"create.image": {
		"description": "A description for the new image",
		"instance":    "The ID of the instance",
		"name":        "A name for the new image",
		"reboot":      "True to shut down and reboot the instance before creating the image, otherwise no reboot and file system integrity on the created image cannot be guaranteed",
	},
	"create.instance": {
		"associate-public-ip": "If true, a public IP address will be assigned to the instance. Requires a subnet to be specified",
		"count":               "The number of instances to launch",
		"distro":              "The distro query to resolve official community free bare distro AMI from current region. See above description from this help for specific queries. Default choices:",
		"image":               "The ID of an AMI for the instance to be launched",
		"ip":                  "The primary IPv4 address",
		"keypair":             "The name of the key pair",
		"lock":                "If you set this parameter to true, you can't terminate the instance using the Amazon EC2 console, CLI, or API; otherwise, you can",
		"ebs-optimized":       "Indicates whether the instance is optimized for Amazon EBS I/O. Recommended for instances that benefit from high throughput to EBS",
		"name":                "The name of the instance to launch",
		"role":                "The name of the instance profile (role) to launch the instance with",
		"securitygroup":       "One or more security group IDs",
		"subnet":              "The ID of the subnet to launch the instance into",
		"type":                "The instance type",
		"userdata":            "The user data to make available to the instance",
	},
	"create.instanceprofile": {
		"name": "The name of the instance profile to create",
	},
	"create.keypair": {
		"encrypted": "Set to 'true' if you want to encrypt the keypair",
		"name":      "The name of the keypair to create (it will also be the name of the file stored in ~/.awless/keys)",
	},
	"create.launchconfiguration": {
		"distro":         "The distro query to resolve official community bare distro AMI from current region. See `awless search images -h`",
		"image":          "The ID of the Amazon Machine Image (AMI) to use to launch your EC2 instances",
		"keypair":        "The name of the key pair",
		"name":           "The name of the launch configuration",
		"public":         "Used for groups that launch instances into a virtual private cloud (VPC). Specifies whether to assign a public IP address to each instance",
		"role":           "The name or the Amazon Resource Name (ARN) of the instance profile associated with the IAM role for the instance",
		"securitygroups": "One or more security groups with which to associate the instances",
		"spotprice":      "The maximum hourly price to be paid for any Spot Instance launched to fulfill the request",
		"type":           "The instance type of the EC2 instance",
		"userdata":       "The user data to make available to the launched EC2 instances",
	},
	"create.listener": {
		"actiontype":   "The type of action",
		"certificate":  "The Amazon Resource Name (ARN) of the certificate",
		"loadbalancer": "The Amazon Resource Name (ARN) of the load balancer",
		"port":         "The port on which the load balancer is listening",
		"protocol":     "The protocol for connections from clients to the load balancer",
		"sslpolicy":    "The security policy that defines which ciphers and protocols are supported",
		"targetgroup":  "The Amazon Resource Name (ARN) of the target group",
	},
	"create.loadbalancer": {
		"iptype":          "[Application Load Balancers] The type of IP addresses used by the subnets for your load balancer",
		"name":            "The name of the load balancer",
		"scheme":          "The nodes of an Internet-facing load balancer have public IP addresses",
		"securitygroups":  "[Application Load Balancers] The IDs of the security groups to assign to the load balancer",
		"subnet-mappings": "The IDs of the subnets to attach to the load balancer",
		"subnets":         "The IDs of the subnets to attach to the load balancer",
		"type":            "The type of load balancer to create",
	},
	"create.loginprofile": {
		"password":       "The new password for the user",
		"password-reset": "Specifies whether the user is required to set a new password on next sign-in",
		"username":       "The name of the IAM user to create a password for",
	},
	"create.mfadevice": {
		"name": "The name of the virtual MFA device",
	},
	"create.natgateway": {
		"elasticip-id": "The allocation ID of an Elastic IP address to associate with the NAT gateway",
		"subnet":       "The subnet in which to create the NAT gateway",
	},
	"create.networkinterface": {
		"description":    "A description for the network interface",
		"privateip":      "The primary private IPv4 address of the network interface",
		"securitygroups": "The IDs of one or more security groups",
		"subnet":         "The ID of the subnet to associate with the network interface",
	},
	"create.policy": {
		"action":      "The Action elements describing the actions that will be allowed or denied. You specify a value using a namespace that identifies a service followed by the name of the action to allow or deny (eg. sqs:SendMessage, s3:*). Use a list for multiple actions",
		"conditions":  "List of conditions necessary for the policy to be in effect (e.g. [aws:UserAgent!=My user agent,s3:prefix=~home/,aws:CurrentTime>=2013-06-30T00:00:00Z,aws:SourceIp!=203.0.113.0/24,aws:SourceArn==arn:aws:sns:eu-west-1:*:*])",
		"description": "A friendly description of the policy",
		"effect":      "The Effect element is required and specifies whether the policy will result in an allow or an explicit deny",
		"name":        "The friendly name of the policy",
		"resource":    "The Amazon Resource Name (ARN) of the Resource element which specifies the object or objects that the policy covers",
	},
	"create.queue": {
		"delay":              "The length of time, in seconds, for which the delivery of all messages in the queue is delayed. Valid values: An integer from 0 to 900 seconds (15 minutes). The default is 0",
		"max-msg-size":       "The limit of how many bytes a message can contain before Amazon SQS rejects it. Valid values: An integer from 1024 bytes (1 KiB) to 262144 bytes (256 KiB). The default is 262144 (256 KiB)",
		"msg-wait":           "The length of time, in seconds, for which a ReceiveMessage action waits for a message to arrive. Valid values: An integer from 0 to 20 (seconds). The default is 0",
		"name":               "The name of the new queue",
		"policy":             "The queue's policy",
		"redrive-policy":     "The parameters for the dead letter queue functionality of the source queue",
		"retention-period":   "The length of time, in seconds, for which Amazon SQS retains a message. Valid values: An integer from 60 seconds (1 minute) to 1209600 seconds (14 days). The default is 345600 (4 days)",
		"visibility-timeout": "The visibility timeout for the queue. Valid values: An integer from 0 to 43200 (12 hours). The default is 30",
	},
	"create.record": {
		"comment": "Any comments you want to include about a change batch request",
		"name":    "The name of the domain you want to perform the action on. Enter a fully qualified domain name, for example, www.example.com. You can optionally include a trailing dot",
		"ttl":     "The resource record cache time to live (TTL), in seconds",
		"type":    "The DNS record type",
		"value":   "The new DNS record value",
		"values":  "The new DNS record value(s)",
		"zone":    "The ID of the hosted zone that contains the resource record sets that you want to change",
	},
	"create.repository": {
		"name": "The name to use for the repository",
	},
	"create.role": {
		"conditions":        "List of conditions necessary for the policy to be in effect (e.g. [aws:UserAgent!=My user agent,s3:prefix=~home/,aws:CurrentTime>=2013-06-30T00:00:00Z,aws:SourceIp!=203.0.113.0/24,aws:SourceArn==arn:aws:sns:eu-west-1:*:*])",
		"name":              "The name of the role to create",
		"principal-account": "The ID of the account that can perform actions and access resources of the role (you can know your account ID with `awless whoami`)",
		"principal-service": "The AWS Service that can assume this role to perform actions and access resources of the role (e.g. 'ec2.amazonaws.com')",
		"principal-user":    "The Amazon Resource Name (ARN) of the user that can perform actions and access resources of the role",
		"sleep-after":       "The amount of time in seconds you want to wait after creating the role (usually used to be sure that the role creation has been propagated)",
	},
	"create.route": {
		"cidr":    "The IPv4 CIDR address block used for the destination match",
		"gateway": "The ID of an Internet gateway or virtual private gateway attached to your VPC",
		"table":   "The ID of the route table for the route",
	},
	"create.routetable": {
		"vpc": "The ID of the VPC",
	},
	"create.s3object": {
		"acl":    "The canned ACL to apply to the object",
		"bucket": "Name of the bucket to which object will be added",
		"file":   "The path toward to file to upload",
		"name":   "The name of the Object to create (by default the file name is used)",
	},
	"create.scalinggroup": {
		"cooldown":                 "The amount of time, in seconds, after a scaling activity completes before another scaling activity can start",
		"desired-capacity":         "The number of EC2 instances that should be running in the group",
		"healthcheck-grace-period": "The amount of time, in seconds, that Auto Scaling waits before checking the health status of an EC2 instance that has come into service",
		"healthcheck-type":         "The service to use for the health checks",
		"launchconfiguration":      "The name of the launch configuration",
		"max-size":                 "The maximum size of the group",
		"min-size":                 "The minimum size of the group",
		"name":                     "The name of the Auto Scaling group",
		"new-instances-protected":  "Indicates whether newly launched instances are protected from termination by Auto Scaling when scaling in",
		"subnets":                  "A comma-separated list of subnet identifiers for your virtual private cloud (VPC)",
		"targetgroups":             "The Amazon Resource Names (ARN) of the target groups",
	},
	"create.scalingpolicy": {
		"adjustment-magnitude": "The minimum number of instances to scale",
		"adjustment-scaling":   "The amount by which to scale, based on the specified adjustment type (e.g. '-2', '3')",
		"adjustment-type":      "The adjustment type",
		"cooldown":             "The amount of time, in seconds, after a scaling activity completes and before the next scaling activity can start",
		"name":                 "The name of the scaling policy",
		"scalinggroup":         "The name of the Auto Scaling group",
	},
	"create.securitygroup": {
		"description": "A description for the security group",
		"name":        "The name of the security group",
		"vpc":         "The ID of the VPC",
	},
	"create.snapshot": {
		"description": "A description for the snapshot",
		"volume":      "The ID of the EBS volume",
	},
	"create.stack": {
		"capabilities":            "A list of values that you must specify before AWS CloudFormation can create certain stacks",
		"disable-rollback":        "Set to true to disable rollback of the stack if stack creation failed",
		"name":                    "The name that is associated with the stack",
		"notifications":           "The Simple Notification Service (SNS) topic ARNs to publish stack related events",
		"on-failure":              "Determines what action will be taken if stack creation fails",
		"parameters":              "A list of Parameters that specify input parameters for the stack given using this format: [key1:val1,key2:val2,...]",
		"policy-file":             "The path to the file containing the stack policy body",
		"resource-types":          "The template resource types that you have permissions to work with for this create stack action, such as AWS::EC2::Instance, AWS::EC2::*, or Custom::MyCustomInstance",
		"role":                    "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that AWS CloudFormation assumes to create the stack",
		"rollback-monitoring-min": "Time to monitor rollback-triggers during and after creation",
		"rollback-triggers":       "List of CloudWatch Alarm ARNs to monitor during and after creation",
		"stack-file":              "The path to the file containing Parameters/Tags/StackPolices definition (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-cfn-artifacts.html#w2ab2c13c15c15). Values passed via CLI has higher priority than ones defined in StackFile",
		"tags":                    "Key-value pairs to associate with this stack",
		"template-file":           "The path to the file containing the template body with a minimum size of 1 byte and a maximum size of 51,200 bytes",
		"timeout":                 "The amount of time that can pass before the stack status becomes CREATE_FAILED; if DisableRollback is not set or is set to false, the stack will be rolled back",
	},
	"create.subnet": {
		"availabilityzone": "The Availability Zone for the subnet",
		"cidr":             "The IPv4 network range for the subnet, in CIDR notation",
		"name":             "The 'Name' Tag for the subnet to create",
		"public":           "A value (true) to indicate that network interfaces created in this subnet should be assigned a public IPv4 address (instances, etc.)",
		"vpc":              "The ID of the VPC",
	},
	"create.subscription": {
		"endpoint": "The endpoint that you want to receive notifications. Endpoints vary by protocol: For the http or https protocol, the endpoint is a URL beginning with 'http://' or 'https://', for the email or email-json protocol, the endpoint is an email address, for the sms protocol, the endpoint is a phone number of an SMS-enabled, for the sqs protocol, the endpoint is the ARN of an Amazon SQS queue, for the application protocol, the endpoint is the EndpointArn of a mobile app and device, for the lambda protocol, the endpoint is the ARN of an AWS Lambda function",
		"protocol": "The protocol you want to use",
		"topic":    "The ARN of the topic you want to subscribe to",
	},
	"create.tag": {
		"key":      "The Tag key",
		"resource": "The ID of the resource on which you want to add a tag",
		"value":    "The Tag value",
	},
	"create.targetgroup": {
		"healthcheckinterval": "The approximate amount of time, in seconds, between health checks of an individual target",
		"healthcheckpath":     "[HTTP/HTTPS health checks] The ping path that is the destination on the targets for health checks",
		"healthcheckport":     "The port the load balancer uses when performing health checks on targets",
		"healthcheckprotocol": "The protocol the load balancer uses when performing health checks on targets",
		"healthchecktimeout":  "The amount of time, in seconds, during which no response from a target means a failed health check",
		"healthythreshold":    "The number of consecutive health checks successes required before considering an unhealthy target healthy",
		"matcher":             "The HTTP codes to use when checking for a successful response from a target",
		"name":                "The name of the target group",
		"port":                "The port on which the targets receive traffic",
		"protocol":            "The protocol to use for routing traffic to the targets",
		"unhealthythreshold":  "The number of consecutive health check failures required before considering a target unhealthy",
		"vpc":                 "The identifier of the virtual private cloud (VPC)",
	},
	"create.topic": {
		"name": "The name of the topic you want to create",
	},
	"create.user": {
		"name": "The name of the user to create",
	},
	"create.volume": {
		"availabilityzone": "The Availability Zone in which to create the volume",
		"size":             "The size of the volume, in GiBs",
	},
	"create.vpc": {
		"cidr": "The IPv4 network range for the VPC, in CIDR notation",
		"name": "The 'Name' Tag for the VPC to create",
	},
	"create.zone": {
		"callerreference": "A unique string that identifies the request and that allows failed CreateHostedZone requests to be retried without the risk of executing the operation twice",
		"comment":         "Any comments that you want to include about the hosted zone",
		"delegationsetid": "If you want to associate a reusable delegation set with this hosted zone, the ID that Amazon Route 53 assigned to the reusable delegation set when you created it",
		"isprivate":       "A value that indicates whether this is a private hosted zone",
		"name":            "The name of the domain",
		"vpcid":           "(Private hosted zones only) The ID of an Amazon VPC",
		"vpcregion":       "(Private hosted zones only) The region in which you created an Amazon VPC",
	},
	"delete.accesskey": {
		"id":   "The ID of the access key and secret access key you want to delete",
		"user": "The name of the user whose access key pair you want to delete",
	},
	"delete.alarm": {
		"name": "The name of the alarm(s) to be deleted",
	},
	"delete.appscalingpolicy": {
		"dimension":         "The scalable dimension",
		"name":              "The name of the scaling policy",
		"resource":          "The identifier of the resource associated with the scalable target",
		"service-namespace": "The namespace of the AWS service",
	},
	"delete.appscalingtarget": {
		"dimension":         "The scalable dimension associated with the scalable target",
		"resource":          "The identifier of the resource associated with the scalable target",
		"service-namespace": "The namespace of the AWS service",
	},
	"delete.bucket": {
		"name": "The name of the bucket to be deleted",
	},
	"delete.certificate": {
		"arn": "String that contains the ARN of the ACM Certificate to be deleted",
	},
	"delete.classicloadbalancer": {
		"name": "The name of the Classic load balancer",
	},
	"delete.containercluster": {
		"id": "The short name or full Amazon Resource Name (ARN) of the cluster to delete",
	},
	"delete.containertask": {
		"all-versions": "Set to 'true' to delete all existing versions of the containertask to be deleted",
		"name":         "The name of the containertask to be deleted",
	},
	"delete.database": {
		"id":            "The ID of the database to be deleted",
		"skip-snapshot": "Determines whether a final DB snapshot is created before the DB instance is deleted. If true is specified, no DBSnapshot is created. If false is specified, a DB snapshot is created before the DB instance is deleted",
		"snapshot":      "The ID of the new DBSnapshot created when skip-snapshot=false",
	},
	"delete.dbsubnetgroup": {
		"name": "The name of the database subnet group to be deleted",
	},
	"delete.distribution": {
		"id": "The ID of the distribution to be deleted",
	},
	"delete.elasticip": {
		"id": "The allocation ID",
		"ip": "The Elastic IP address",
	},
	"delete.function": {
		"id":      "The ID of the Lambda function to be deleted",
		"version": "Using this optional parameter you can specify a function version (but not the $LATEST version) to direct AWS Lambda to delete a specific function version",
	},
	"delete.group": {
		"name": "The name of the IAM group to delete",
	},
	"delete.image": {
		"delete-snapshots": "Set to 'true' to also delete the snapshots created from this image",
		"id":               "The ID of the AMI to be deleted",
	},
	"delete.instance": {
		"id":  "The ID of the instance(s) to be deleted",
		"ids": "The ID(s) of the instance(s) to be deleted",
	},
	"delete.instanceprofile": {
		"name": "The name of the instance profile to delete",
	},
	"delete.internetgateway": {
		"id": "The ID of the Internet gateway to be deleted",
	},
	"delete.keypair": {
		"name": "The name of the key pair to be deleted",
	},
	"delete.launchconfiguration": {
		"name": "The name of the launch configuration to be deleted",
	},
	"delete.listener": {
		"id": "The Amazon Resource Name (ARN) of the listener",
	},
	"delete.loadbalancer": {
		"id": "The Amazon Resource Name (ARN) of the load balancer",
	},
	"delete.loginprofile": {
		"username": "The name of the user whose password you want to delete",
	},
	"delete.mfadevice": {
		"id": "The serial number that uniquely identifies the MFA device",
	},
	"delete.natgateway": {
		"id": "The ID of the NAT gateway",
	},
	"delete.networkinterface": {
		"id": "The ID of the network interface",
	},
	"delete.policy": {
		"all-versions": "Set to 'true' to delete all existing versions of the policy to be deleted",
		"arn":          "The Amazon Resource Name (ARN) of the IAM policy you want to delete",
	},
	"delete.queue": {
		"url": "The URL of the Amazon SQS queue to delete",
	},
	"delete.record": {
		"id":     "The awless id (cf `awless list records`) of the record to delete",
		"name":   "The name of the domain you want to perform the action on. Enter a fully qualified domain name, for example, www.example.com. You can optionally include a trailing dot",
		"ttl":    "The resource record cache time to live (TTL), in seconds",
		"type":   "The DNS record type",
		"value":  "The DNS record value to delete",
		"values": "The DNS record value(s) to delete",
		"zone":   "The ID of the hosted zone that contains the resource record sets that you want to delete",
	},
	"delete.repository": {
		"account": "The AWS account ID associated with the registry that contains the repository to delete",
		"force":   "If a repository contains images, forces the deletion",
		"name":    "The name of the repository to delete",
	},
	"delete.role": {
		"name": "The name of the role to be deleted",
	},
	"delete.route": {
		"cidr":  "The IPv4 CIDR range for the route",
		"table": "The ID of the route table",
	},
	"delete.routetable": {
		"id": "The ID of the route table",
	},
	"delete.s3object": {
		"bucket": "The name of the bucket containing the object to be deleted",
		"name":   "The name (i.e. key) of the object to be deleted",
	},
	"delete.scalinggroup": {
		"force": "Specifies that the group will be deleted along with all instances associated with the group, without waiting for all instances to be terminated",
		"name":  "The name of the Auto Scaling group",
	},
	"delete.scalingpolicy": {
		"id": "The name or Amazon Resource Name (ARN) of the policy",
	},
	"delete.securitygroup": {
		"id": "The ID of the security group",
	},
	"delete.snapshot": {
		"id": "The ID of the EBS snapshot",
	},
	"delete.stack": {
		"name":             "The name or the unique stack ID that is associated with the stack",
		"retain-resources": "For stacks in the DELETE_FAILED state, a list of resource logical IDs that are associated with the resources you want to retain",
	},
	"delete.subnet": {
		"id": "The ID of the subnet",
	},
	"delete.subscription": {
		"id": "The ARN of the subscription to be deleted",
	},
	"delete.tag": {
		"key":      "The Tag key",
		"resource": "The ID of the resource on which you want to remove a tag",
		"value":    "The Tag value",
	},
	"delete.targetgroup": {
		"id": "The Amazon Resource Name (ARN) of the target group",
	},
	"delete.topic": {
		"id": "The ARN of the topic you want to delete",
	},
	"delete.user": {
		"name": "The name of the user to delete",
	},
	"delete.volume": {
		"id": "The ID of the volume",
	},
	"delete.vpc": {
		"id": "The ID of the VPC",
	},
	"delete.zone": {
		"id": "The ID of the hosted zone you want to delete",
	},
	"detach.alarm": {
		"action-arn": "The Amazon Resource Name (ARN) to be detached of the ALARM actions",
		"name":       "The name of the alarm",
	},
	"detach.classicloadbalancer": {
		"instance": "The ID of the instance",
		"name":     "The name of the Classic load balancer",
	},
	"detach.containertask": {
		"container-name": "The name of the container to detach",
		"name":           "The name of the existing container task containing the container to detach",
	},
	"detach.elasticip": {
		"association": "The association ID",
	},
	"detach.instance": {
		"id":          "The ID of the instance to be detached from target group",
		"targetgroup": "The Amazon Resource Name (ARN) of the target group",
	},
	"detach.instanceprofile": {
		"instance": "The ID of the Instance",
		"name":     "The name of the InstanceProfile to detach from the Instance",
	},
	"detach.internetgateway": {
		"id":  "The ID of the Internet gateway",
		"vpc": "The ID of the VPC",
	},
	"detach.mfadevice": {
		"id":   "The serial number that uniquely identifies the MFA device",
		"user": "The name of the user whose MFA device you want to deactivate",
	},
	"detach.networkinterface": {
		"attachment": "The ID of the attachment",
		"force":      "Specifies whether to force a detachment",
		"id":         "The ID of the network interface",
		"instance":   "The ID of the instance this network interface is attached to",
	},
	"detach.policy": {
		"access":  "Type of access to retrieve an AWS policy",
		"arn":     "The Amazon Resource Name (ARN) of the IAM policy you want to detach",
		"group":   "The name (friendly name, not ARN) of the IAM group to detach the policy to",
		"role":    "The name (friendly name, not ARN) of the IAM role to detach the policy to",
		"service": "Service string to retrieve an AWS policy",
		"user":    "The name (friendly name, not ARN) of the IAM user to detach the policy to",
	},
	"detach.role": {
		"instanceprofile": "The name of the instance profile to update",
		"name":            "The name of the role to remove",
	},
	"detach.routetable": {
		"association": "The association ID representing the current association between the route table and subnet",
	},
	"detach.securitygroup": {
		"id":       "The ID of the security group",
		"instance": "The ID of the instance to be detached",
	},
	"detach.user": {
		"group": "The name of the group to update",
		"name":  "The name of the user to remove",
	},
	"detach.volume": {
		"device":   "The device name",
		"force":    "Forces detachment if the previous detachment attempt did not occur cleanly (for example, logging into an instance, unmounting the volume, and detaching normally)",
		"id":       "The ID of the volume",
		"instance": "The ID of the instance",
	},
	"import.image": {
		"architecture": "The architecture of the virtual machine",
		"bucket":       "The name of the S3 bucket where the disk image is located",
		"description":  "A description string for the import image task",
		"license":      "The license type to be used for the Amazon Machine Image (AMI) after importing",
		"platform":     "The operating system of the virtual machine",
		"role":         "The name of the role to use when not using the default role, 'vmimport'",
		"s3object":     "The name of the S3 object where the disk image is located",
		"snapshot":     "The ID of the EBS snapshot to be used for importing the snapshot",
		"url":          "The URL to the Amazon S3-based disk image being imported. The URL can either be a https URL (https://..) or an Amazon S3 URL (s3://..)",
	},
	"restart.database": {
		"id":            "Contains a user-supplied database identifier",
		"with-failover": "When true, the reboot is conducted through a MultiAZ failover",
	},
	"restart.instance": {
		"id":  "The ID of the instance to be restarted",
		"ids": "One or more instance IDs",
	},
	"start.alarm": {
		"names": "The names of the alarms",
	},
	"start.containertask": {
		"cluster":                     "The short name or full Amazon Resource Name (ARN) of the cluster on which to run your task",
		"deployment-name":             "The deployment name of the service (e.g. prod, staging...)",
		"desired-count":               "The number of instantiations of the specified service to place and keep running on your cluster",
		"loadbalancer.container-name": "The name of the container (as it appears in a container definition) to associate with the load balancer",
		"loadbalancer.container-port": "The port on the container to associate with the load balancer",
		"loadbalancer.targetgroup":    "The full Amazon Resource Name (ARN) of the Elastic Load Balancing target group associated with a service",
		"name":                        "The name of the container task to start",
		"role":                        "The name or full Amazon Resource Name (ARN) of the IAM role that allows Amazon ECS to make calls to your load balancer on your behalf",
		"type":                        "The type of task to launch",
	},
	"start.database": {
		"id": "Contains a user-supplied database identifier",
	},
	"start.instance": {
		"id":  "The ID of the instance to be started",
		"ids": "One or more instance IDs",
	},
	"stop.alarm": {
		"names": "The names of the alarms",
	},
	"stop.containertask": {
		"cluster":         "The short name or full Amazon Resource Name (ARN) of the cluster on which to run your task",
		"deployment-name": "The deployment name of the service (e.g. prod, staging...)",
		"run-arn":         "The ID or full Amazon Resource Name (ARN) entry of the run of the task to stop",
		"type":            "The type of task to launch",
	},
	"stop.database": {
		"id": "Contains a user-supplied database identifier",
	},
	"stop.instance": {
		"id":  "The ID of the instance to be stopped",
		"ids": "One or more instance IDs",
	},
	"update.bucket": {
		"acl":               "The canned ACL to apply to the bucket",
		"enforce-https":     "Use HTTPS rather than HTTP when redirecting requests",
		"index-suffix":      "A suffix that is appended to a request that is for a directory on the website endpoint",
		"name":              "The name of the bucket to update",
		"public-website":    "Set to 'true' if you want to publish the content of the bucket as a public HTTP website",
		"redirect-hostname": "Hostname where HTTP requests will be redirected when publishing website",
	},
	"update.classicloadbalancer": {
		"health-interval":     "The approximate interval, in seconds, between health checks of an individual instance",
		"health-target":       "String with format PROTOCOL:PORT[PING_PATH]. For HTTP/HTTPS, you must include a ping path. Protocols: TCP, HTTP, HTTPS, or SSL. Ex: TCP:5000, or HTTP:80/weather/us/wa/seattle",
		"health-timeout":      "The amount of time, in seconds, during which no response means a failed health check. This value must be less than the Interval value",
		"healthy-threshold":   "The number of consecutive health checks successes required before moving the instance to the Healthy state",
		"name":                "The name of the load balancer",
		"unhealthy-threshold": "The number of consecutive health check failures required before moving the instance to the Unhealthy state",
	},
	"update.containertask": {
		"cluster":         "The short name or full Amazon Resource Name (ARN) of the cluster that your service is running on",
		"deployment-name": "The name of the service to update",
		"desired-count":   "The number of instantiations of the task to place and keep running in your service",
		"name":            "The family and revision (family:revision) or full ARN of the task definition to run in your service",
	},
	"update.distribution": {
		"certificate":     "The Amazon Resource Name (ARN) of the AWS Certificate Manager (ACM) certificate you want to use for TSL connection",
		"comment":         "Any comments you want to include about the distribution",
		"default-file":    "The object that you want CloudFront to request from your origin when a viewer requests the root URL for your distribution (http://www.example.com)",
		"domain-aliases":  "A list of CNAMEs (alternate domain names), if any, for this distribution",
		"enable":          "Enable/Disable the distribution",
		"forward-cookies": "Specifies which cookies to forward to the origin for this cache behavior",
		"forward-queries": "Indicates whether you want CloudFront to forward query strings to the origin that is associated with this cache behavior and cache based on the query string parameters (true | false)",
		"https-behavior":  "The protocol (HTTP or HTTPS) that viewers can use to access the files",
		"id":              "The ID of the distribution to update",
		"min-ttl":         "The minimum amount of time that you want objects to stay in CloudFront caches before CloudFront forwards another request to your origin to determine whether the object has been updated",
		"origin-domain":   "The DNS name of the Amazon S3 bucket from which you want CloudFront to get objects for this origin, for example, myawsbucket.s3.amazonaws.com",
		"origin-path":     "An optional element that causes CloudFront to request your content from a directory in your Amazon S3 bucket or your custom origin. When you include this element, specify the directory name, beginning with a /",
		"price-class":     "The price class that corresponds with the maximum price that you want to pay for CloudFront service. If you specify PriceClass_All, CloudFront responds to requests for your objects from all CloudFront edge locations",
	},
	"update.image": {
		"accounts":      "List (one or more) AWS account IDs",
		"description":   "A new description for the AMI",
		"groups":        "List (one or more) user groups",
		"id":            "The ID of the AMI",
		"operation":     "The operation type for launch permissions",
		"product-codes": "One or more DevPay product codes. After adding a product code, it cannot be removed",
	},
	"update.instance": {
		"id":   "The ID of the instance",
		"lock": "If the value is true, you can't terminate the instance using the Amazon EC2 console, CLI, or API; otherwise, you can",
		"type": "Changes the instance type to the specified value",
	},
	"update.loginprofile": {
		"password":       "The new password for the specified IAM user",
		"password-reset": "Allows this new password to be used only once by requiring the specified IAM user to set a new password on next sign-in",
		"username":       "The name of the user whose password you want to update",
	},
	"update.policy": {
		"action":     "The Action elements describing the actions that will be allowed or denied. You specify a value using a namespace that identifies a service followed by the name of the action to allow or deny (eg. sqs:SendMessage, s3:*). Use a list for multiple actions",
		"arn":        "The Amazon Resource Name (ARN) of the IAM policy you want to attach",
		"conditions": "List of conditions necessary for the policy to be in effect (e.g. [aws:UserAgent!=My user agent,s3:prefix=~home/,aws:CurrentTime>=2013-06-30T00:00:00Z,aws:SourceIp!=203.0.113.0/24,aws:SourceArn==arn:aws:sns:eu-west-1:*:*])",
		"effect":     "The Effect element is required and specifies whether the policy will result in an allow or an explicit deny",
		"resource":   "The Amazon Resource Name (ARN) of the Resource element which specifies the object or objects that the policy covers",
	},
	"update.record": {
		"comment": "Any comments you want to include about a change batch request",
		"name":    "The name of the domain you want to perform the action on. Enter a fully qualified domain name, for example, www.example.com. You can optionally include a trailing dot",
		"ttl":     "The resource record cache time to live (TTL), in seconds",
		"type":    "The DNS record type",
		"value":   "The current or new DNS record value",
		"values":  "The current or new DNS record value(s)",
		"zone":    "The ID of the hosted zone that contains the resource record sets that you want to change",
	},
	"update.s3object": {
		"acl":     "The canned ACL to apply to the bucket",
		"bucket":  "The name of the bucket containing the object to be updated",
		"name":    "The name of the object to be updated",
		"version": "Used to reference a specific version of the object",
	},
	"update.scalinggroup": {
		"cooldown":                 "The amount of time, in seconds, after a scaling activity completes before another scaling activity can start",
		"desired-capacity":         "The number of EC2 instances that should be running in the Auto Scaling group",
		"healthcheck-grace-period": "The amount of time, in seconds, that Auto Scaling waits before checking the health status of an EC2 instance that has come into service",
		"healthcheck-type":         "The service to use for the health checks",
		"launchconfiguration":      "The name of the launch configuration",
		"max-size":                 "The maximum size of the Auto Scaling group",
		"min-size":                 "The minimum size of the Auto Scaling group",
		"name":                     "The name of the Auto Scaling group",
		"new-instances-protected":  "Indicates whether newly launched instances are protected from termination by Auto Scaling when scaling in",
		"subnets":                  "The ID of the subnet, if you are launching into a VPC",
	},
	"update.securitygroup": {
		"cidr":          "The CIDR IPv4 address range",
		"id":            "The ID of the security group to be updated",
		"inbound":       "Set inbound to either authorize or revoke, to update the security group ingress rules",
		"outbound":      "Set outbound to either authorize or revoke, to update the security group egress rules",
		"portrange":     "The portrange for the rule to update: any, 80, 22-23...",
		"protocol":      "The IP protocol name or number",
		"securitygroup": "The ID of the source security group. Cannot be used when using cidr param",
	},
	"update.stack": {
		"capabilities":            "A list of values that you must specify before AWS CloudFormation can update certain stacks",
		"name":                    "The name or unique stack ID of the stack to update",
		"notifications":           "Amazon Simple Notification Service topic Amazon Resource Names (ARNs) that AWS CloudFormation associates with the stack",
		"parameters":              "A list of Parameters that specify input parameters for the stack given using this format: [key1:val1,key2:val2,...]",
		"policy-file":             "The path to the file containing the stack policy body",
		"policy-update-file":      "The path to the file containing the temporary overriding stack policy",
		"resource-types":          "The template resource types that you have permissions to work with for this update stack action, such as AWS::EC2::Instance, AWS::EC2::*, or Custom::MyCustomInstance",
		"role":                    "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that AWS CloudFormation assumes to update the stack",
		"rollback-monitoring-min": "Time to monitor rollback-triggers during and after update",
		"rollback-triggers":       "List of CloudWatch Alarm ARNs to monitor during and after update",
		"stack-file":              "The path to the file containing Parameters/Tags/StackPolices definition (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-cfn-artifacts.html#w2ab2c13c15c15). Values passed via CLI has higher priority than ones defined in StackFile",
		"tags":                    "Key-value pairs to associate with this stack",
		"template-file":           "The path to the file containing the template body with a minimum size of 1 byte and a maximum size of 51,200 bytes",
		"use-previous-template":   "Reuse the existing template that is associated with the stack that you are updating",
	},
	"update.subnet": {
		"id":     "The ID of the subnet",
		"public": "Specify true to indicate that network interfaces created in the specified subnet should be assigned a public IPv4 address",
	},
	"update.targetgroup": {
		"deregistrationdelay": "The amount time for Elastic Load Balancing to wait before changing the state of a deregistering target from draining to unused. The range is 0-3600 seconds. The default value is 300 seconds",
		"healthcheckinterval": "The approximate amount of time, in seconds, between health checks of an individual target",
		"healthcheckpath":     "The ping path that is the destination on the targets for health checks",
		"healthcheckport":     "The port the load balancer uses when performing health checks on targets",
		"healthcheckprotocol": "The protocol the load balancer uses when performing health checks on targets",
		"healthchecktimeout":  "The amount of time, in seconds, during which no response from a target means a failed health check",
		"healthythreshold":    "The number of consecutive health checks successes required before considering an unhealthy target healthy",
		"id":                  "The Amazon Resource Name (ARN) of the target group",
		"matcher":             "The HTTP codes to use when checking for a successful response from a target",
		"name":                "The name of the target group",
		"port":                "The port on which the targets receive traffic",
		"protocol":            "The protocol to use for routing traffic to the targets",
		"stickiness":          "Indicates whether sticky sessions (of type load balancer cookies) are enabled",
		"stickinessduration":  "The time period, in seconds, during which requests from a client should be routed to the same target. After this time period expires, the load balancer-generated cookie is considered stale. The range is 1 second to 1 week (604800 seconds). The default value is 1 day (86400 seconds)",
		"unhealthythreshold":  "The number of consecutive health check failures required before considering a target unhealthy",
	},
}
